---
sidebar: sidebar 
permalink: trident-docker/upgrade-uninstall-docker.html 
keywords: uninstall, Trident, trident for docker, docker, upgrade trident for docker 
summary: 'Vous pouvez mettre à niveau Trident pour Docker en toute sécurité, sans aucun impact sur les volumes en cours d"utilisation.  Durant le processus de mise à niveau, il y aura une brève période pendant laquelle `docker volume` Les commandes adressées au plugin échoueront et les applications ne pourront pas monter de volumes tant que le plugin ne sera pas de nouveau en cours d"exécution.  Dans la plupart des cas, cela se prend en quelques secondes.' 
---
= Mettez à jour ou désinstallez Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau Trident pour Docker en toute sécurité, sans aucun impact sur les volumes en cours d'utilisation.  Durant le processus de mise à niveau, il y aura une brève période pendant laquelle `docker volume` Les commandes adressées au plugin échoueront et les applications ne pourront pas monter de volumes tant que le plugin ne sera pas de nouveau en cours d'exécution.  Dans la plupart des cas, cela se prend en quelques secondes.



== Mise à niveau

Suivez les étapes ci-dessous pour mettre à niveau Trident pour Docker.

.Étapes
. Liste des volumes existants :
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. Désactiver le plugin :
+
[listing]
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Mettre à jour le plugin :
+
[listing]
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+

NOTE: La version 18.01 de Trident remplace le nDVP.  Vous devriez effectuer la mise à niveau directement depuis le `netapp/ndvp-plugin` l'image à l' `netapp/trident-plugin` image.

. Activez le plugin :
+
[listing]
----
docker plugin enable netapp:latest
----
. Vérifiez que le plugin est activé :
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. Vérifiez que les volumes sont visibles :
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----



IMPORTANT: Si vous effectuez une mise à niveau depuis une ancienne version de Trident (antérieure à la version 20.10) vers Trident 20.10 ou une version ultérieure, vous pourriez rencontrer une erreur.  Pour plus d'informations, veuillez consulterlink:known-issues-docker.html["Problèmes connus"^] .  Si vous rencontrez cette erreur, vous devez d'abord désactiver le plugin, puis le supprimer, et enfin installer la version requise de Trident en passant un paramètre de configuration supplémentaire : `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`



== Désinstaller

Suivez les étapes ci-dessous pour désinstaller Trident pour Docker.

.Étapes
. Supprimez tous les volumes créés par le plugin.
. Désactiver le plugin :
+
[listing]
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Supprimez le plugin :
+
[listing]
----
docker plugin rm netapp:latest
----

