---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: 'Pour créer des volumes, utilisez la méthode standard `docker volume` commandes avec le nom du pilote Trident spécifié lorsque nécessaire.' 
---
= Travailler avec des volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez facilement créer, cloner et supprimer des volumes à l'aide de la norme `docker volume` commandes avec le nom du pilote Trident spécifié lorsque nécessaire.



== Créer un volume

* Créez un volume avec un pilote utilisant le nom par défaut :
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* Créer un volume avec une instance Trident spécifique :
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: Si vous ne spécifiez rienlink:volume-driver-options.html["options"^] , les paramètres par défaut du pilote sont utilisés.

* Remplacez la taille de volume par défaut. Consultez l'exemple suivant pour créer un volume de 20 Gio avec un pilote :
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: Les tailles de volume sont exprimées sous forme de chaînes de caractères contenant une valeur entière avec des unités facultatives (exemple : 10G, 20GB, 3TiB).  Si aucune unité n'est spécifiée, la valeur par défaut est G. Les unités de taille peuvent être exprimées soit en puissances de 2 (B, KiB, MiB, GiB, TiB), soit en puissances de 10 (B, KB, MB, GB, TB).  Les unités abrégées utilisent des puissances de 2 (G = GiB, T = TiB, …).





== Supprimer un volume

* Supprimez le volume comme n'importe quel autre volume Docker :
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT: Lors de l'utilisation du `solidfire-san` Le pilote, dans l'exemple ci-dessus, supprime et purge le volume.



Suivez les étapes ci-dessous pour mettre à niveau Trident pour Docker.



== Cloner un volume

Lors de l'utilisation du `ontap-nas` , `ontap-san` , `solidfire-san` , et `gcp-cvs storage drivers` Trident peut cloner des volumes.  Lors de l'utilisation du `ontap-nas-flexgroup` ou `ontap-nas-economy` Le clonage des pilotes n'est pas pris en charge.  La création d'un nouveau volume à partir d'un volume existant entraînera la création d'un nouvel instantané.

* Examinez le volume pour énumérer les instantanés :
+
[source, console]
----
docker volume inspect <volume_name>
----
* Créer un nouveau volume à partir d'un volume existant.  Cela entraînera la création d'un nouvel instantané :
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* Créer un nouveau volume à partir d'un instantané existant sur un volume.  Cela ne créera pas de nouvel instantané :
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== Exemple

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== Accéder aux volumes créés en externe

Vous pouvez accéder aux périphériques de stockage par blocs créés en externe (ou à leurs clones) par des conteneurs utilisant Trident *uniquement* s'ils ne comportent aucune partition et si leur système de fichiers est pris en charge par Trident (par exemple : un `ext4` -formaté `/dev/sdc1` ne sera pas accessible via Trident).
