---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: 'Chaque pilote de stockage possède un ensemble d"options différent, que vous pouvez spécifier lors de la création du volume pour personnaliser le résultat.  Vous trouverez ci-dessous les options qui s"appliquent à votre système de stockage configuré.' 
---
= Options de volume spécifiques au conducteur
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque pilote de stockage possède un ensemble d'options différent, que vous pouvez spécifier lors de la création du volume pour personnaliser le résultat.  Vous trouverez ci-dessous les options qui s'appliquent à votre système de stockage configuré.

L'utilisation de ces options lors de la création d'un volume est simple.  Indiquez l'option et la valeur en utilisant `-o` opérateur pendant l'opération CLI.  Ces valeurs remplacent toutes les valeurs équivalentes du fichier de configuration JSON.



== options de volume ONTAP

Les options de création de volumes pour NFS, iSCSI et FC incluent les suivantes :

[cols="2*"]
|===
| Option | Description 


| `size`  a| 
La taille du volume est par défaut de 1 Gio.



| `spaceReserve`  a| 
Le volume peut être mince ou épais ; par défaut, mince.  Les valeurs valides sont `none` (à faible capacité) et `volume` (provisionné épais).



| `snapshotPolicy`  a| 
Cela définira la politique de capture d'écran sur la valeur souhaitée.  La valeur par défaut est `none` , ce qui signifie qu'aucun instantané ne sera automatiquement créé pour le volume.  Sauf modification par votre administrateur de stockage, une politique nommée « default » existe sur tous les systèmes ONTAP qui crée et conserve six instantanés horaires, deux instantanés quotidiens et deux instantanés hebdomadaires.  Les données conservées dans un instantané peuvent être récupérées en accédant à l'URL. `.snapshot` répertoire dans n'importe quel répertoire du volume.



| `snapshotReserve`  a| 
Cela permettra de définir la réserve d'instantanés au pourcentage souhaité.  La valeur par défaut est aucune, ce qui signifie ONTAP sélectionnera snapshotReserve (généralement 5 %) si vous avez sélectionné une snapshotPolicy, ou 0 % si aucune snapshotPolicy n'est définie.  Vous pouvez définir la valeur par défaut de snapshotReserve dans le fichier de configuration pour tous les backends ONTAP , et vous pouvez l'utiliser comme option de création de volume pour tous les backends ONTAP à l'exception de ontap-nas-economy.



| `splitOnClone`  a| 
Lors du clonage d'un volume, ONTAP séparera immédiatement le clone de son parent.  La valeur par défaut est `false` .  Dans certains cas d'utilisation du clonage de volumes, il est préférable de séparer immédiatement le clone de son parent dès sa création, car il est peu probable qu'il y ait des possibilités d'optimisation du stockage.  Par exemple, le clonage d'une base de données vide peut permettre un gain de temps important mais un gain de stockage minime ; il est donc préférable de scinder immédiatement le clone.



| `encryption`  a| 
Activez le chiffrement de volume NetApp (NVE) sur le nouveau volume ; la valeur par défaut est `false` .  Pour utiliser cette option, NVE doit être sous licence et activé sur le cluster.

Si NAE est activé sur le système dorsal, tout volume provisionné dans Trident sera compatible NAE.

Pour plus d'informations, veuillez consulter :link:../trident-reco/security-reco.html["Comment Trident fonctionne avec NVE et NAE"] .



| `tieringPolicy`  a| 
Définit la politique de hiérarchisation à utiliser pour le volume.  Cela détermine si les données sont déplacées vers le niveau cloud lorsqu'elles deviennent inactives (froides).

|===
Les options supplémentaires suivantes concernent *uniquement* NFS :

[cols="2*"]
|===
| Option | Description 


| `unixPermissions`  a| 
Ceci contrôle les autorisations définies pour le volume lui-même.  Par défaut, les autorisations seront définies sur ``---rwxr-xr-x` , ou en notation numérique 0755, et `root` sera le propriétaire.  Le format texte ou numérique conviendra.



| `snapshotDir`  a| 
Définir ceci à `true` fera le `.snapshot` Répertoire visible par les clients accédant au volume.  La valeur par défaut est `false` , ce qui signifie que la visibilité de `.snapshot` Ce répertoire est désactivé par défaut.  Certaines images, par exemple l'image officielle de MySQL, ne fonctionnent pas comme prévu lorsque `.snapshot` Le répertoire est visible.



| `exportPolicy`  a| 
Définit la politique d'exportation à utiliser pour le volume.  La valeur par défaut est `default` .



| `securityStyle`  a| 
Définit le style de sécurité à utiliser pour l'accès au volume.  La valeur par défaut est `unix` .  Les valeurs valides sont `unix` et `mixed` .

|===
Les options supplémentaires suivantes concernent uniquement iSCSI :

[cols="2*"]
|===
| Option | Description 


| `fileSystemType` | Définit le système de fichiers utilisé pour formater les volumes iSCSI.  La valeur par défaut est `ext4` .  Les valeurs valides sont `ext3` , `ext4` , et `xfs` . 


| `spaceAllocation` | Définir ceci à `false` désactivera la fonction d'allocation d'espace du LUN.  La valeur par défaut est `true` , ce qui signifie ONTAP notifie l'hôte lorsque le volume est à court d'espace et que le LUN du volume ne peut plus accepter d'écritures.  Cette option permet également à ONTAP de récupérer automatiquement l'espace lorsque votre hôte supprime des données. 
|===


=== Exemples

Voir les exemples ci-dessous :

* Créer un volume de 10 Gio :
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* Créer un volume de 100 Gio avec des instantanés :
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* Créez un volume dont le bit setUID est activé :
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


La taille minimale du volume est de 20 Mio.

Si la réserve d'instantanés n'est pas spécifiée et que la stratégie d'instantanés est `none` Trident utilise une réserve d'instantanés de 0 %.

* Créer un volume sans stratégie de snapshot et sans réserve de snapshot :
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* Créez un volume sans stratégie de snapshot et avec une réserve de snapshot personnalisée de 10 % :
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* Créez un volume avec une stratégie de snapshot et une réserve de snapshot personnalisée de 10 % :
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* Créez un volume avec une stratégie de snapshot et acceptez la réserve de snapshot par défaut d'ONTAP (généralement 5 %) :
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== options de volume du logiciel Element

Les options du logiciel Element exposent la taille et les politiques de qualité de service (QoS) associées au volume.  Lors de la création du volume, la politique QoS qui lui est associée est spécifiée à l'aide de `-o type=service_level` nomenclature.

La première étape pour définir un niveau de service QoS avec le pilote Element consiste à créer au moins un type et à spécifier les IOPS minimales, maximales et en rafale associées à un nom dans le fichier de configuration.

Les autres options de création de volumes du logiciel Element incluent les suivantes :

[cols="2*"]
|===
| Option | Description 


| `size`  a| 
La taille du volume, par défaut 1 Gio ou entrée de configuration... "defaults": {"size": "5G"}.



| `blocksize`  a| 
Utilisez 512 ou 4096, la valeur par défaut est 512 ou l'entrée de configuration DefaultBlockSize.

|===


=== Exemple

Voir l'exemple de fichier de configuration suivant avec les définitions QoS :

[source, json]
----
{
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----
Dans la configuration ci-dessus, nous avons trois définitions de politique : Bronze, Argent et Or.  Ces noms sont arbitraires.

* Créer un volume Gold de 10 Gio :
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* Créer un volume Bronze de 100 Gio :
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

