---
sidebar: sidebar 
permalink: faq.html 
keywords: faq, frequently asked questions 
summary: 'Trouvez les réponses aux questions fréquemment posées concernant l"installation, la configuration, la mise à niveau et le dépannage de Trident.' 
---
= Foire aux questions
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Trouvez les réponses aux questions fréquemment posées concernant l'installation, la configuration, la mise à niveau et le dépannage de Trident.



== Questions générales



=== À quelle fréquence Trident est-il mis à jour ?

À compter de la version 24.02, Trident sort tous les quatre mois : février, juin et octobre.



=== Trident prend-il en charge toutes les fonctionnalités publiées dans une version particulière de Kubernetes ?

Trident ne prend généralement pas en charge les fonctionnalités alpha dans Kubernetes.  Trident pourrait prendre en charge des fonctionnalités bêta dans les deux versions de Trident qui suivront la version bêta de Kubernetes.



=== Trident dépend-il d'autres produits NetApp pour fonctionner ?

Trident ne dépend d'aucun autre produit logiciel NetApp et fonctionne comme une application autonome.  Toutefois, vous devez disposer d'un périphérique de stockage dorsal NetApp .



=== Comment puis-je obtenir les détails complets de la configuration Trident ?

Utilisez le `tridentctl get` commande permettant d'obtenir plus d'informations sur votre configuration Trident .



=== Puis-je obtenir des statistiques sur la manière dont le stockage est provisionné par Trident?

Oui. Points de terminaison Prometheus pouvant être utilisés pour recueillir des informations sur le fonctionnement de Trident , telles que le nombre de serveurs backend gérés, le nombre de volumes provisionnés, les octets consommés, etc.  Vous pouvez également utiliserlink:https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights"^] pour le suivi et l'analyse.



=== L'expérience utilisateur est-elle modifiée lors de l'utilisation de Trident en tant que fournisseur CSI ?

Non. Il n'y a aucun changement en ce qui concerne l'expérience utilisateur et les fonctionnalités.  Le nom du fournisseur utilisé est `csi.trident.netapp.io` .  Cette méthode d'installation de Trident est recommandée si vous souhaitez utiliser toutes les nouvelles fonctionnalités offertes par les versions actuelles et futures.



== Installer et utiliser Trident sur un cluster Kubernetes



=== Trident prend-il en charge l'installation hors ligne à partir d'un registre privé ?

Oui, Trident peut être installé hors ligne. Se référer àlink:../trident-get-started/kubernetes-deploy.html["Découvrez l'installation de Trident"^] .



=== Puis-je installer Trident à distance ?

Oui. Trident 18.10 et versions ultérieures prennent en charge l'installation à distance depuis n'importe quelle machine disposant de `kubectl` accès au cluster.  Après `kubectl` L'accès est vérifié (par exemple, initier une `kubectl get nodes` (commande depuis la machine distante pour vérifier), suivez les instructions d'installation.



=== Puis-je configurer la haute disponibilité avec Trident?

Trident est installé en tant que déploiement Kubernetes (ReplicaSet) avec une seule instance, et intègre donc la haute disponibilité. Il est déconseillé d'augmenter le nombre de réplicas dans le déploiement.  Si le nœud sur lequel Trident est installé est perdu ou si le pod est inaccessible, Kubernetes redéploie automatiquement le pod sur un nœud sain de votre cluster.  Le Trident ne concerne que le plan de contrôle ; les nacelles actuellement installées ne sont donc pas affectées en cas de redéploiement du Trident .



=== Trident a-t-il besoin d'accéder à l'espace de noms kube-system ?

Trident lit les données du serveur d'API Kubernetes pour déterminer quand les applications demandent de nouveaux PVC ; il a donc besoin d'accéder à kube-system.



=== Quels sont les rôles et les privilèges utilisés par Trident?

Le programme d'installation Trident crée un Kubernetes ClusterRole, qui dispose d'un accès spécifique aux ressources PersistentVolume, PersistentVolumeClaim, StorageClass et Secret du cluster Kubernetes. Se référer àlink:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personnaliser l'installation de tridentctl"^] .



=== Puis-je générer localement les fichiers manifestes exacts utilisés par Trident pour l'installation ?

Vous pouvez générer et modifier localement, si nécessaire, les fichiers manifestes exacts utilisés par Trident pour l'installation. Se référer àlink:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personnaliser l'installation de tridentctl"^] .



=== Puis-je partager le même SVM backend ONTAP pour deux instances Trident distinctes pour deux clusters Kubernetes distincts ?

Bien que cela ne soit pas conseillé, vous pouvez utiliser le même SVM backend pour deux instances Trident .  Spécifiez un nom de volume unique pour chaque instance lors de l'installation et/ou spécifiez un nom de volume unique `StoragePrefix` paramètre dans le `setup/backend.json` déposer.  Ceci afin de garantir que le même FlexVol volume ne soit pas utilisé dans les deux cas.



=== Est-il possible d'installer Trident sous ContainerLinux (anciennement CoreOS) ?

Trident est simplement un pod Kubernetes et peut être installé partout où Kubernetes est exécuté.



=== Puis-je utiliser Trident avec NetApp Cloud Volumes ONTAP?

Oui, Trident est compatible avec AWS, Google Cloud et Azure.



=== Trident est-il compatible avec Cloud Volumes Services ?

Oui, Trident prend en charge le service Azure NetApp Files dans Azure ainsi que le Cloud Volumes Service dans GCP.



== Dépannage et assistance



=== NetApp prend-il en charge Trident?

Bien que Trident soit un logiciel libre et gratuit, NetApp le prend entièrement en charge à condition que votre système dorsal NetApp soit compatible.



=== Comment puis-je ouvrir un dossier d'assistance ?

Pour ouvrir une demande de prise en charge, procédez comme suit :

. Contactez votre responsable de compte d'assistance et obtenez de l'aide pour créer un ticket.
. Ouvrez un ticket d'assistance en contactant https://www.netapp.com/company/contact-us/support/["Assistance NetApp"^] .




=== Comment générer un bundle de journal de support ?

Vous pouvez créer un ensemble de support en exécutant `tridentctl logs -a` .  En plus des journaux capturés dans le bundle, capturez le journal kubelet pour diagnostiquer les problèmes de montage côté Kubernetes.  Les instructions pour obtenir le journal kubelet varient en fonction de la manière dont Kubernetes est installé.



=== Que dois-je faire si je dois soumettre une demande pour une nouvelle fonctionnalité ?

Créer un problème sur https://github.com/NetApp/trident["Trident Github"^] et mentionnez *RFE* dans l'objet et la description du problème.



=== Où dois-je signaler un défaut ?

Créer un problème sur https://github.com/NetApp/trident["Trident Github"^] .  Veillez à inclure toutes les informations et tous les journaux nécessaires relatifs au problème.



=== Que se passe-t-il si j'ai une question rapide sur Trident sur laquelle j'ai besoin d'éclaircissements ?  Existe-t-il une communauté ou un forum ?

Si vous avez des questions, des problèmes ou des demandes, contactez-nous via notre Tridentlink:https://discord.gg/NetApp["Chaîne Discord"^] ou GitHub.



=== Le mot de passe de mon système de stockage a changé et Trident ne fonctionne plus. Comment puis-je le récupérer ?

Mettez à jour le mot de passe du backend avec `tridentctl update backend myBackend -f </path/to_new_backend.json> -n trident` .  Remplacer `myBackend` dans l'exemple avec le nom de votre backend, et ``/path/to_new_backend.json` avec le chemin vers le bon `backend.json` déposer.



=== Trident ne trouve pas mon nœud Kubernetes.  Comment puis-je résoudre ce problème ?

Deux scénarios sont susceptibles d'expliquer pourquoi Trident ne trouve pas de nœud Kubernetes.  Cela peut être dû à un problème de réseau au sein de Kubernetes ou à un problème DNS.  Le daemonset de nœud Trident qui s'exécute sur chaque nœud Kubernetes doit pouvoir communiquer avec le contrôleur Trident pour enregistrer le nœud auprès de Trident.  Si des modifications du réseau sont survenues après l'installation de Trident , vous ne rencontrerez ce problème qu'avec les nouveaux nœuds Kubernetes ajoutés au cluster.



=== Si la capsule Trident est détruite, vais-je perdre les données ?

Aucune donnée ne sera perdue en cas de destruction de la capsule Trident .  Les métadonnées Trident sont stockées dans des objets CRD.  Tous les PV provisionnés par Trident fonctionneront normalement.



== Amélioration du Trident



=== Puis-je passer directement d'une version antérieure à une version plus récente (en sautant quelques versions) ?

NetApp prend en charge la mise à niveau de Trident d'une version majeure à la version majeure suivante.  Vous pouvez passer de la version 18.xx à la version 19.xx, de la version 19.xx à la version 20.xx, et ainsi de suite.  Il est conseillé de tester la mise à niveau en laboratoire avant le déploiement en production.



=== Est-il possible de revenir à une version antérieure de Trident ?

Si vous avez besoin d'un correctif pour des bogues observés après une mise à niveau, des problèmes de dépendances ou une mise à niveau incomplète ou ayant échoué, vous devriezlink:trident-managing-k8s/uninstall-trident.html["désinstaller Trident"] et réinstallez la version précédente en suivant les instructions spécifiques à cette version.  Il s'agit de la seule méthode recommandée pour revenir à une version antérieure.



== Gérer les backends et les volumes



=== Dois-je définir à la fois les LIF de gestion et de données dans un fichier de définition backend ONTAP ?

La LIF de gestion est obligatoire.  DataLIF varie :

* SAN ONTAP : Ne pas spécifier pour iSCSI.  Trident utiliselink:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Carte LUN sélective ONTAP"^] pour découvrir les LIF iSCI nécessaires à l'établissement d'une session multi-chemin.  Un avertissement est généré si `dataLIF` est explicitement défini. Se référer à link:trident-use/ontap-san-examples.html["Options et exemples de configuration SAN ONTAP"] pour plus de détails.
* ONTAP NAS : NetApp recommande de spécifier `dataLIF` .  Si aucune donnée n'est fournie, Trident récupère les dataLIF à partir du SVM.  Vous pouvez spécifier un nom de domaine pleinement qualifié (FQDN) à utiliser pour les opérations de montage NFS, ce qui vous permet de créer un DNS à répartition circulaire pour équilibrer la charge sur plusieurs dataLIF.  Se référer àlink:trident-use/ontap-nas-examples.html["Options et exemples de configuration ONTAP NAS"] pour plus de détails




=== Trident peut-il configurer CHAP pour les systèmes backend ONTAP ?

Oui. Trident prend en charge le protocole CHAP bidirectionnel pour les systèmes backend ONTAP .  Cela nécessite de paramétrer `useCHAP=true` dans votre configuration backend.



=== Comment gérer les politiques d'exportation avec Trident?

Trident peut créer et gérer dynamiquement des politiques d'exportation à partir de la version 20.04.  Cela permet à l'administrateur de stockage de fournir un ou plusieurs blocs CIDR dans sa configuration backend et de faire en sorte que Trident ajoute les adresses IP des nœuds qui se trouvent dans ces plages à une politique d'exportation qu'il crée.  De cette manière, Trident gère automatiquement l'ajout et la suppression de règles pour les nœuds dont les adresses IP se situent dans les CIDR spécifiés.



=== Les adresses IPv6 peuvent-elles être utilisées pour les LIF de gestion et de données ?

Trident prend en charge la définition d'adresses IPv6 pour :

* `managementLIF`et `dataLIF` pour les serveurs NAS ONTAP .
* `managementLIF`pour les backends SAN ONTAP .  Vous ne pouvez pas spécifier `dataLIF` sur un système dorsal SAN ONTAP .


Trident doit être installé à l'aide du drapeau `--use-ipv6` (pour `tridentctl` installation), `IPv6` (pour opérateur Trident ), ou `tridentTPv6` (pour l'installation de Helm) pour qu'il fonctionne sur IPv6.



=== Est-il possible de mettre à jour le LIF de gestion côté serveur ?

Oui, il est possible de mettre à jour le LIF de gestion backend à l'aide de `tridentctl update backend` commande.



=== Est-il possible de mettre à jour le DataLIF côté serveur ?

Vous pouvez mettre à jour le DataLIF sur `ontap-nas` et `ontap-nas-economy` seulement.



=== Est-il possible de créer plusieurs backends dans Trident pour Kubernetes ?

Trident peut prendre en charge simultanément plusieurs serveurs dorsaux, avec le même pilote ou des pilotes différents.



=== Comment Trident stocke-t-il les identifiants du serveur ?

Trident stocke les identifiants du backend sous forme de secrets Kubernetes.



=== Comment Trident sélectionne-t-il un serveur dorsal spécifique ?

Si les attributs du backend ne peuvent pas être utilisés pour sélectionner automatiquement les pools appropriés pour une classe, `storagePools` et `additionalStoragePools` Des paramètres sont utilisés pour sélectionner un ensemble spécifique de pools.



=== Comment puis-je m'assurer que Trident ne sera pas provisionné à partir d'un serveur dorsal spécifique ?

Le `excludeStoragePools` Ce paramètre sert à filtrer l'ensemble des pools que Trident utilise pour le provisionnement et supprimera tous les pools correspondants.



=== S'il existe plusieurs serveurs dorsaux du même type, comment Trident sélectionne-t-il celui à utiliser ?

S'il existe plusieurs serveurs backend configurés du même type, Trident sélectionne le serveur backend approprié en fonction des paramètres présents dans `StorageClass` et `PersistentVolumeClaim` .  Par exemple, s'il existe plusieurs backends de pilotes ontap-nas, Trident tente de faire correspondre les paramètres dans le `StorageClass` et `PersistentVolumeClaim` combinés et adaptés à un backend capable de répondre aux exigences énumérées dans `StorageClass` et `PersistentVolumeClaim` .  S'il existe plusieurs serveurs backend correspondant à la requête, Trident en sélectionne un au hasard.



=== Trident prend-il en charge le protocole CHAP bidirectionnel avec Element/ SolidFire?

Oui.



=== Comment Trident déploie-t-il des Qtrees sur un volume ONTAP ?  Combien de Qtrees peuvent être déployés sur un seul volume ?

Le `ontap-nas-economy` Le pilote crée jusqu'à 200 Qtrees dans le même FlexVol volume (configurable entre 50 et 300), 100 000 Qtrees par nœud de cluster et 2,4 millions par cluster.  Lorsque vous entrez dans un nouveau `PersistentVolumeClaim` qui est pris en charge par le pilote économique, ce dernier vérifie s'il existe déjà un FlexVol volume capable de prendre en charge le nouveau Qtree.  Si aucun FlexVol volume ne peut prendre en charge l'arbre Qtree, un nouveau FlexVol volume est créé.



=== Comment puis-je configurer les permissions Unix pour les volumes provisionnés sur un NAS ONTAP ?

Vous pouvez définir les permissions Unix sur le volume provisionné par Trident en définissant un paramètre dans le fichier de définition du backend.



=== Comment puis-je configurer un ensemble explicite d'options de montage NFS ONTAP lors du provisionnement d'un volume ?

Par défaut, Trident ne configure aucune option de montage avec Kubernetes.  Pour spécifier les options de montage dans la classe de stockage Kubernetes, suivez l'exemple fourni.link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-ontapnas-k8s1.8-mountoptions.yaml["ici"^] .



=== Comment puis-je configurer les volumes provisionnés selon une politique d'exportation spécifique ?

Pour autoriser les hôtes appropriés à accéder à un volume, utilisez le `exportPolicy` Paramètre configuré dans le fichier de définition du backend.



=== Comment configurer le chiffrement des volumes via Trident avec ONTAP?

Vous pouvez configurer le chiffrement du volume provisionné par Trident en utilisant le paramètre de chiffrement dans le fichier de définition du backend.  Pour plus d'informations, veuillez consulter :link:trident-reco/security-reco.html#use-trident-with-nve-and-nae["Comment Trident fonctionne avec NVE et NAE"]



=== Quelle est la meilleure façon de mettre en œuvre la QoS pour ONTAP via Trident?

Utiliser `StorageClasses` implémenter la QoS pour ONTAP.



=== Comment puis-je spécifier un provisionnement fin ou épais via Trident?

Les pilotes ONTAP prennent en charge le provisionnement fin ou épais.  Les pilotes ONTAP utilisent par défaut le provisionnement fin.  Si le provisionnement épais est souhaité, vous devez configurer soit le fichier de définition du backend, soit le `StorageClass` .  Si les deux sont configurés, `StorageClass` a priorité.  Configurez les éléments suivants pour ONTAP:

. Sur `StorageClass` , définissez le `provisioningType` Attribut : épais.
. Dans le fichier de définition du backend, activez les volumes épais en configurant `backend spaceReserve parameter` en volume.




=== Comment puis-je m'assurer que les volumes utilisés ne sont pas supprimés même si je supprime accidentellement le PVC ?

La protection PVC est automatiquement activée sur Kubernetes à partir de la version 1.10.



=== Puis-je cultiver des PVC NFS créées par Trident?

Oui. Vous pouvez dilater un PVC créé par Trident.  Notez que l'extension automatique des volumes est une fonctionnalité ONTAP qui ne s'applique pas à Trident.



=== Puis-je importer un volume alors qu'il est en mode SnapMirror Data Protection (DP) ou en mode hors ligne ?

L'importation du volume échoue si le volume externe est en mode DP ou hors ligne.  Vous recevez le message d'erreur suivant :

[listing]
----
Error: could not import volume: volume import failed to get size of volume: volume <name> was not found (400 Bad Request) command terminated with exit code 1.
Make sure to remove the DP mode or put the volume online before importing the volume.
----


=== Comment le quota de ressources est-il traduit dans un cluster NetApp ?

Le système de quotas de ressources de stockage Kubernetes devrait fonctionner tant que le stockage NetApp dispose de capacités.  Lorsque le stockage NetApp ne peut pas respecter les paramètres de quota Kubernetes en raison d'un manque de capacité, Trident tente de provisionner mais génère une erreur.



=== Puis-je créer des instantanés de volume avec Trident?

Oui. La création d'instantanés de volumes à la demande et de volumes persistants à partir d'instantanés est prise en charge par Trident.  Pour créer des PV à partir d'instantanés, assurez-vous que les `VolumeSnapshotDataSource` La fonctionnalité de contrôle d'accès a été activée.



=== Quels sont les pilotes qui prennent en charge les instantanés de volume Trident ?

À compter d'aujourd'hui, la prise en charge des instantanés à la demande est disponible pour notre `ontap-nas` , `ontap-nas-flexgroup` , `ontap-san` , `ontap-san-economy` , `solidfire-san` , `gcp-cvs` , et `azure-netapp-files` Pilotes backend.



=== Comment puis-je effectuer une sauvegarde instantanée d'un volume provisionné par Trident avec ONTAP?

Ceci est disponible sur `ontap-nas` , `ontap-san` , et `ontap-nas-flexgroup` conducteurs.  Vous pouvez également spécifier un `snapshotPolicy` pour le `ontap-san-economy` pilote au niveau FlexVol .

Ceci est également disponible sur le `ontap-nas-economy` pilotes, mais au niveau de granularité du FlexVol volume et non au niveau de granularité de l'arbre qtree.  Pour activer la possibilité de créer des instantanés des volumes provisionnés par Trident, définissez l'option du paramètre backend. `snapshotPolicy` à la politique de snapshot souhaitée telle que définie sur le backend ONTAP .  Trident ne connaît pas les instantanés pris par le contrôleur de stockage.



=== Puis-je définir un pourcentage de réserve d'instantané pour un volume provisionné via Trident?

Oui, vous pouvez réserver un pourcentage spécifique d'espace disque pour stocker les copies d'instantanés via Trident en configurant le `snapshotReserve` attribut dans le fichier de définition du backend.  Si vous avez configuré `snapshotPolicy` et `snapshotReserve` Dans le fichier de définition du backend, le pourcentage de réserve de snapshots est défini en fonction de `snapshotReserve` pourcentage mentionné dans le fichier backend.  Si le `snapshotReserve` Le pourcentage n'est pas mentionné ; par défaut, ONTAP prend un pourcentage de réserve de snapshot de 5.  Si le `snapshotPolicy` L'option est définie sur aucune, le pourcentage de réserve d'instantané est défini sur 0.



=== Puis-je accéder directement au répertoire des instantanés de volume et copier des fichiers ?

Oui, vous pouvez accéder au répertoire des instantanés sur le volume provisionné par Trident en configurant le `snapshotDir` paramètre dans le fichier de définition du backend.



=== Puis-je configurer SnapMirror pour les volumes via Trident?

Actuellement, SnapMirror doit être configuré en externe à l'aide de l'interface de ligne de commande ONTAP ou du OnCommand System Manager.



=== Comment restaurer des volumes persistants à partir d'un instantané ONTAP spécifique ?

Pour restaurer un volume à partir d'un instantané ONTAP , procédez comme suit :

. Mettez en veille le pod d'application qui utilise le volume persistant.
. Revenez à l'instantané requis via l'interface de ligne de commande ONTAP ou OnCommand System Manager.
. Redémarrez le pod d'application.




=== Trident peut-il provisionner des volumes sur des SVM ayant un miroir de partage de charge configuré ?

Des miroirs à répartition de charge peuvent être créés pour les volumes racine des SVM qui diffusent des données via NFS.  ONTAP met automatiquement à jour les miroirs de partage de charge pour les volumes créés par Trident.  Cela peut entraîner des retards dans le montage des volumes.  Lorsque plusieurs volumes sont créés à l'aide de Trident, le provisionnement d'un volume dépend de la mise à jour par ONTAP du miroir de partage de charge.



=== Comment puis-je séparer l'utilisation des classes de stockage pour chaque client/locataire ?

Kubernetes n'autorise pas les classes de stockage dans les espaces de noms.  Cependant, vous pouvez utiliser Kubernetes pour limiter l'utilisation d'une classe de stockage spécifique par espace de noms en utilisant des quotas de ressources de stockage, qui sont par espace de noms.  Pour refuser à un espace de noms spécifique l'accès à un stockage spécifique, définissez le quota de ressources à 0 pour cette classe de stockage.
