---
sidebar: sidebar 
permalink: legal-notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: 'Les mentions légales donnent accès aux déclarations de droits d"auteur, aux marques déposées, aux brevets et bien plus encore.' 
---
= Mentions légales
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les mentions légales donnent accès aux déclarations de droits d'auteur, aux marques déposées, aux brevets et bien plus encore.



== Copyright

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marques de commerce

NETAPP, le logo NETAPP et les marques répertoriées sur la page Marques NetApp sont des marques commerciales de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques commerciales de leurs propriétaires respectifs.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Brevets

Une liste actuelle des brevets détenus par NetApp est disponible à l'adresse suivante :

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Politique de confidentialité

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Open source

Vous pouvez consulter les droits d'auteur et les licences de tiers utilisés dans le logiciel NetApp pour Trident dans le fichier de notices de chaque version à l'adresse suivante : https://github.com/NetApp/trident/[] .
