---
sidebar: sidebar 
permalink: trident-managing-k8s/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Apprenez-en davantage sur tridentctl, un utilitaire en ligne de commande qui offre un accès simple à Trident. 
---
= Gérez Trident à l'aide de tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le https://github.com/NetApp/trident/releases["Pack d'installation Trident"^] comprend le `tridentctl` utilitaire en ligne de commande pour fournir un accès simple à Trident.  Les utilisateurs de Kubernetes disposant de privilèges suffisants peuvent l'utiliser pour installer Trident ou gérer l'espace de noms contenant le pod Trident .



== Commandes et drapeaux globaux

Vous pouvez courir `tridentctl help` pour obtenir la liste des commandes disponibles pour `tridentctl` ou ajouter le `--help` Utilisez l'option `--flag` avec n'importe quelle commande pour obtenir la liste des options et des indicateurs disponibles pour cette commande spécifique.

`tridentctl [command] [--optional-flag]`

Le Trident `tridentctl` Cet utilitaire prend en charge les commandes et les options globales suivantes.

.Commandes
[%collapsible]
====
`create`:: Ajouter une ressource à Trident.
`delete`:: Supprimer une ou plusieurs ressources de Trident.
`get`:: Obtenez une ou plusieurs ressources de Trident.
`help`:: Aide concernant n'importe quelle commande.
`images`:: Imprimez un tableau des images conteneurs nécessaires à Trident .
`import`:: Importer une ressource existante dans Trident.
`install`:: Installez Trident.
`logs`:: Imprimer les journaux de Trident.
`send`:: Envoyer une ressource depuis Trident.
`uninstall`:: Désinstallez Trident.
`update`:: Modifier une ressource dans Trident.
`update backend state`:: Suspension temporaire des opérations en arrière-plan.
`upgrade`:: Mettre à niveau une ressource dans Trident.
`version`:: Imprimez la version de Trident.


====
.drapeaux du monde
[%collapsible]
====
`-d`, `--debug`:: Sortie de débogage.
`-h`, `--help`:: Aide pour `tridentctl` .
`-k`, `--kubeconfig string`:: Précisez le `KUBECONFIG` chemin d'exécution des commandes localement ou d'un cluster Kubernetes à un autre.
+
--

NOTE: Vous pouvez également exporter le `KUBECONFIG` variable permettant de pointer vers un cluster Kubernetes spécifique et de résoudre le problème `tridentctl` commandes à ce cluster.

--
`-n`, `--namespace string`:: Espace de noms du déploiement Trident .
`-o`, `--output string`:: Format de sortie.  L'un des formats json|yaml|name|wide|ps (par défaut).
`-s`, `--server string`:: Adresse/port de l'interface REST de Trident .
+
--

WARNING: L'interface REST de Trident peut être configurée pour écouter et servir uniquement à l'adresse 127.0.0.1 (pour IPv4) ou [::1] (pour IPv6).

--


====


== Options de commande et drapeaux



=== créer

Utilisez le `create` commande pour ajouter une ressource à Trident.

`tridentctl create [option]`

Options:: `backend`: Ajouter un backend à Trident.




=== supprimer

Utilisez le `delete` commande permettant de supprimer une ou plusieurs ressources de Trident.

`tridentctl delete [option]`

Options:: `backend`: Supprimez un ou plusieurs backends de stockage de Trident.
`snapshot` : Supprimez un ou plusieurs instantanés de volume de Trident.
`storageclass` : Supprimez une ou plusieurs classes de stockage de Trident.
`volume` : Supprimez un ou plusieurs volumes de stockage de Trident.




=== obtenir

Utilisez le `get` commande pour obtenir une ou plusieurs ressources de Trident.

`tridentctl get [option]`

Options:: `backend`Obtenez un ou plusieurs backends de stockage auprès de Trident.
`snapshot` : Obtenez un ou plusieurs instantanés de Trident.
`storageclass` : Obtenez une ou plusieurs classes de stockage de Trident.
`volume` Procurez-vous un ou plusieurs volumes chez Trident.
drapeaux:: `-h`, `--help` : Aide pour les volumes.
`--parentOfSubordinate string` Limiter la requête au volume de la source subordonnée.
`--subordinateOf string` Limiter la requête aux subordonnés du volume.




=== images

Utiliser `images` drapeaux permettant d'imprimer un tableau des images de conteneurs dont Trident a besoin.

`tridentctl images [flags]`

drapeaux:: `-h`, `--help` Aide pour les images.
`-v` , `--k8s-version string` : Version sémantique du cluster Kubernetes.




=== volume d'importation

Utilisez le `import volume` commande pour importer un volume existant dans Trident.

`tridentctl import volume <backendName> <volumeName> [flags]`

Alias:: `volume`, `v`
drapeaux:: `-f`, `--filename string` : Chemin d'accès au fichier PVC YAML ou JSON.
`-h` , `--help` : Aide pour le volume.
`--no-manage` : Créer uniquement des PV/PVC.  Ne présumez pas de la gestion du cycle de vie des volumes.




=== installer

Utilisez le `install` options pour installer Trident.

`tridentctl install [flags]`

drapeaux:: `--autosupport-image string`: L'image conteneur pour la télémétrie Autosupport (par défaut « netapp/trident autosupport:<version-actuelle> »).
`--autosupport-proxy string` : Adresse/port d'un proxy pour l'envoi des données de télémétrie Autosupport.
`--enable-node-prep` Tentative d'installation des paquets requis sur les nœuds.
`--generate-custom-yaml` Générez des fichiers YAML sans rien installer.
`-h` , `--help` : Aide à l'installation.
`--http-request-timeout` : Remplacer le délai d'expiration de la requête HTTP pour l'API REST du contrôleur Trident (par défaut 1 min 30 s).
`--image-registry string` : Adresse/port d'un registre d'images interne.
`--k8s-timeout duration` : Le délai d'expiration pour toutes les opérations Kubernetes (par défaut 3m0s).
`--kubelet-dir string` : Emplacement hôte de l'état interne de kubelet (par défaut « /var/lib/kubelet »).
`--log-format string` : Le format de journalisation Trident (texte, json) (par défaut "texte").
`--node-prep` : Permet à Trident de préparer les nœuds du cluster Kubernetes à gérer les volumes à l'aide du protocole de stockage de données spécifié.  *Actuellement, `iscsi` est la seule valeur prise en charge.  À partir d'OpenShift 4.19, la version minimale de Trident prise en charge pour cette fonctionnalité est la 25.06.1.*
`--pv string` : Le nom du PV hérité utilisé par Trident, garantit que celui-ci n'existe pas (par défaut « trident »).
`--pvc string` : Le nom du PVC hérité utilisé par Trident, garantit que celui-ci n'existe pas (par défaut « trident »).
`--silence-autosupport` : Ne pas envoyer automatiquement les bundles d'autosupport à NetApp (valeur par défaut : vrai).
`--silent` Désactiver la plupart des sorties pendant l'installation.
`--trident-image string` : L'image Trident à installer.
`--k8s-api-qps` : La limite de requêtes par seconde (QPS) pour les requêtes API Kubernetes (par défaut 100 ; optionnel).
`--use-custom-yaml` Utilisez les fichiers YAML existants dans le répertoire d'installation.
`--use-ipv6` Utilisez IPv6 pour la communication de Trident.




=== journaux

Utiliser `logs` options pour imprimer les journaux de Trident.

`tridentctl logs [flags]`

drapeaux:: `-a`, `--archive` : Créer une archive de support contenant tous les journaux, sauf indication contraire.
`-h` , `--help` Aide pour les journaux.
`-l` , `--log string` : Affichage du journal Trident .  L'un des trident|auto|trident-operator|all (par défaut "auto").
`--node string` : Nom du nœud Kubernetes à partir duquel collecter les journaux des pods.
`-p` , `--previous` Récupérez les journaux de l'instance de conteneur précédente, si elle existe.
`--sidecars` Récupérez les journaux des conteneurs sidecar.




=== envoyer

Utilisez le `send` commande pour envoyer une ressource depuis Trident.

`tridentctl send [option]`

Options:: `autosupport`: Envoyer une archive Autosupport à NetApp.




=== désinstaller

Utiliser `uninstall` options pour désinstaller Trident.

`tridentctl uninstall [flags]`

drapeaux:: `-h, --help`Aide à la désinstallation.
`--silent` Désactiver la plupart des sorties lors de la désinstallation.




=== mise à jour

Utilisez le `update` commande pour modifier une ressource dans Trident.

`tridentctl update [option]`

Options:: `backend`: Mettre à jour un backend dans Trident.




=== mettre à jour l'état du backend

Utilisez le `update backend state` commande permettant de suspendre ou de reprendre les opérations en arrière-plan.

`tridentctl update backend state <backend-name> [flag]`

.Points à considérer
* Si un backend est créé à l'aide d'un TridentBackendConfig (tbc), il ne peut pas être mis à jour à l'aide d'un `backend.json` déposer.
* Si le `userState` a été défini dans une date limite, il ne peut pas être modifié à l'aide de `tridentctl update backend state <backend-name> --user-state suspended/normal` commande.
* Pour retrouver la capacité de régler `userState` via tridentctl après avoir été configuré via tbc, le `userState` Ce champ doit être supprimé du fichier tbc.  Cela peut être fait en utilisant le `kubectl edit tbc` commande.  Après le `userState` Le champ a été supprimé, vous pouvez utiliser le `tridentctl update backend state` commande pour modifier la `userState` d'un backend.
* Utilisez le `tridentctl update backend state` pour changer le `userState` .  Vous pouvez également mettre à jour le `userState` en utilisant `TridentBackendConfig` ou `backend.json` fichier ; cela déclenche une réinitialisation complète du système dorsal et peut prendre du temps.
+
drapeaux:: `-h`, `--help` : Aide pour l'état du backend.
`--user-state` : Définir sur `suspended` interrompre les opérations en arrière-plan.  Réglé sur `normal` pour reprendre les opérations en arrière-plan.  Lorsqu'il est réglé sur `suspended` :


* `AddVolume`et `Import Volume` sont en pause.
* `CloneVolume`, `ResizeVolume` , `PublishVolume` , `UnPublishVolume` , `CreateSnapshot` , `GetSnapshot` , `RestoreSnapshot` , `DeleteSnapshot` , `RemoveVolume` , `GetVolumeExternal` , `ReconcileNodeAccess` restent disponibles.


Vous pouvez également mettre à jour l'état du backend en utilisant `userState` champ dans le fichier de configuration du backend `TridentBackendConfig` ou `backend.json` .  Pour plus d'informations, veuillez consulterlink:../trident-use/backend_options.html["Options pour la gestion des backends"] etlink:../trident-use/backend_ops_kubectl.html["Effectuez la gestion du backend avec kubectl"] .

*Exemple:*

[role="tabbed-block"]
====
.JSON
--
Suivez ces étapes pour mettre à jour le `userState` en utilisant le `backend.json` déposer:

. Modifier le `backend.json` fichier à inclure le `userState` champ dont la valeur est définie sur « suspendu ».
. Mettez à jour le backend en utilisant le `tridentctl update backend` la commande et le chemin d'accès à la version mise à jour `backend.json` déposer.
+
*Exemple*: `tridentctl update backend  -f /<path to backend JSON file>/backend.json -n trident`



[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "<redacted>",
  "svm": "nas-svm",
  "backendName": "customBackend",
  "username": "<redacted>",
  "password": "<redacted>",
  "userState": "suspended"
}

----
--
.YAML
--
Vous pouvez modifier le tbc après son application en utilisant `kubectl edit <tbc-name> -n <namespace>` commande.  L'exemple suivant met à jour l'état du backend pour le suspendre en utilisant le `userState: suspended` option:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas
spec:
  version: 1
  backendName: customBackend
  storageDriverName: ontap-nas
  managementLIF: <redacted>
  svm: nas-svm
  userState: suspended
  credentials:
    name: backend-tbc-ontap-nas-secret
----
--
====


=== version

Utiliser `version` drapeaux pour imprimer la version de `tridentctl` et le service Trident en fonctionnement.

`tridentctl version [flags]`

drapeaux:: `--client`Version client uniquement (aucun serveur requis).
`-h, --help` : Aide pour la version.




== Prise en charge des plugins

Tridentctl prend en charge des plugins similaires à kubectl.  Tridentctl détecte un plugin si le nom du fichier binaire du plugin suit le schéma « tridentctl-<plugin> », et si le binaire est situé dans un dossier répertorié dans la variable d'environnement PATH.  Tous les plugins détectés sont répertoriés dans la section plugins de l'aide de tridentctl.  Vous pouvez également limiter la recherche en spécifiant un dossier de plugins dans la variable d'environnement TRIDENTCTL_PLUGIN_PATH (Exemple : `TRIDENTCTL_PLUGIN_PATH=~/tridentctl-plugins/` ).  Si la variable est utilisée, tridenctl effectue la recherche uniquement dans le dossier spécifié.
