---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, Trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: 'Vous devez utiliser la même méthode pour désinstaller Trident que celle utilisée pour l" installer.  Si vous rencontrez des problèmes de bogues après une mise à niveau, des problèmes de dépendances ou une mise à niveau incomplète ou ayant échoué, vous devez désinstaller Trident et réinstaller la version précédente en suivant les instructions spécifiques à cette version.' 
---
= Désinstaller Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez utiliser la même méthode pour désinstaller Trident que celle utilisée pour l' installer.

.À propos de cette tâche
* Si vous rencontrez des problèmes de bogues après une mise à niveau, des problèmes de dépendances ou une mise à niveau incomplète ou ayant échoué, vous devez désinstaller Trident et réinstaller la version précédente en suivant les instructions spécifiques.link:../earlier-versions.html["version"] .  Il s'agit de la seule méthode recommandée pour revenir à une version antérieure.
* Pour faciliter la mise à niveau et la réinstallation, la désinstallation de Trident ne supprime pas les CRD ni les objets associés créés par Trident.  Si vous devez supprimer complètement Trident et toutes ses données, veuillez consulter la documentation.link:../troubleshooting.html#completely-remove-trident-and-crds["Supprimer complètement Trident et CRD"] .


.Avant de commencer
Si vous mettez hors service des clusters Kubernetes, vous devez supprimer toutes les applications qui utilisent des volumes créés par Trident avant la désinstallation.  Cela garantit que les PVC sont dépubliées sur les nœuds Kubernetes avant d'être supprimées.



== Déterminer la méthode d'installation d'origine

Vous devez utiliser la même méthode pour désinstaller Trident que celle utilisée pour l'installer.  Avant de désinstaller, vérifiez quelle version vous avez utilisée pour installer Trident à l'origine.

. Utiliser `kubectl get pods -n trident` pour examiner les gousses.
+
** En l'absence de nacelle opérateur, Trident a été installé via `tridentctl` .
** S'il existe un module opérateur, Trident a été installé à l'aide de l'opérateur Trident , soit manuellement, soit via Helm.


. S'il y a une cabine d'opérateur, utilisez-la `kubectl describe tproc trident` pour déterminer si Trident a été installé à l'aide de Helm.
+
** Si une étiquette Helm est présente, Trident a été installé à l'aide de Helm.
** S'il n'y a pas d'étiquette Helm, Trident a été installé manuellement à l'aide de l'opérateur Trident .






== Désinstaller une installation d'opérateur Trident

Vous pouvez désinstaller une installation de l'opérateur Trident manuellement ou à l'aide de Helm.



=== Désinstaller l'installation manuelle

Si vous avez installé Trident à l'aide de l'opérateur, vous pouvez le désinstaller en procédant de l'une des manières suivantes :

. **Modifier `TridentOrchestrator` CR et définissez l'indicateur de désinstallation** :
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
Quand le `uninstall` L'indicateur est réglé sur `true` L'opérateur Trident désinstalle Trident, mais ne supprime pas TridentOrchestrator lui-même.  Vous devriez nettoyer le TridentOrchestrator et en créer un nouveau si vous souhaitez réinstaller Trident .

. **Supprimer `TridentOrchestrator` **: En supprimant le `TridentOrchestrator` CR qui a été utilisé pour déployer Trident, vous demandez à l'opérateur de désinstaller Trident.  L'opérateur traite le retrait de `TridentOrchestrator` et procède à la suppression du déploiement Trident et du daemonset, en supprimant les pods Trident qu'il avait créés dans le cadre de l'installation.
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== Désinstaller Helm

Si vous avez installé Trident à l'aide de Helm, vous pouvez le désinstaller en utilisant `helm uninstall` .

[listing]
----
#List the Helm release corresponding to the Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== Désinstaller un `tridentctl` installation

Utilisez le `uninstall` commande dans `tridentctl` supprimer toutes les ressources associées à Trident, à l'exception des CRD et des objets associés :

[listing]
----
./tridentctl uninstall -n <namespace>
----