---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'Vous pouvez facilement mettre à niveau une installation Trident existante à l"aide de l"opérateur.' 
---
= Mettez à niveau une installation Trident à l'aide de l'opérateur Trident ou de Helm.
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à niveau Trident à l'aide de l'opérateur Trident , soit manuellement, soit via Helm.  Vous pouvez effectuer une mise à niveau d'une installation d'opérateur Trident vers une autre installation d'opérateur Trident ou effectuer une mise à niveau depuis une `tridentctl` installation sur une version opérateur Trident .  Revoirlink:upgrade-trident.html#select-an-upgrade-method["Sélectionnez une méthode de mise à niveau"] avant de mettre à niveau une installation d'opérateur Trident .



== Mise à niveau d'une installation manuelle

Vous pouvez effectuer une mise à niveau d'une installation d'opérateur Trident à l'échelle d'un cluster vers une autre installation d'opérateur Trident à l'échelle d'un cluster. Toutes les versions de Trident utilisent un opérateur à portée de cluster.


NOTE: Pour mettre à niveau une version de Trident installée à l'aide de l'opérateur à portée d'espace de noms (versions 20.07 à 20.10), suivez les instructions de mise à niveau pourlink:../earlier-versions.html["votre version installée"] de Trident.

.À propos de cette tâche
Trident fournit un fichier bundle que vous pouvez utiliser pour installer l'opérateur et créer les objets associés pour votre version de Kubernetes.

* Pour les clusters exécutant Kubernetes 1.24, utilisezlink:https://github.com/NetApp/trident/tree/stable/v25.02/deploy/bundle_pre_1_25.yaml["bundle_pre_1_25.yaml"^] .
* Pour les clusters exécutant Kubernetes 1.25 ou une version ultérieure, utilisezlink:https://github.com/NetApp/trident/tree/stable/v25.02/deploy/bundle_post_1_25.yaml["bundle_post_1_25.yaml"^] .


.Avant de commencer
Assurez-vous d'utiliser un cluster Kubernetes en cours d'exécution.link:../trident-get-started/requirements.html["une version Kubernetes prise en charge"] .

.Étapes
. Vérifiez votre version de Trident :
+
[listing]
----
./tridentctl -n trident version
----
. Mettre à jour `operator.yaml` , `tridentorchestrator_cr.yaml` , et `post_1_25_bundle.yaml` avec le registre et les chemins d'accès aux images pour la version vers laquelle vous effectuez la mise à niveau (par exemple 25.06), et le secret correct.
. Supprimez l’opérateur Trident qui a été utilisé pour installer l’instance Trident actuelle. Par exemple, si vous effectuez une mise à niveau à partir de la version 25.02, exécutez la commande suivante :
+
[listing]
----
kubectl delete -f 25.02.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. Si vous avez personnalisé votre installation initiale en utilisant `TridentOrchestrator` les attributs, vous pouvez les modifier `TridentOrchestrator` objet permettant de modifier les paramètres d'installation.  Cela peut inclure des modifications apportées pour spécifier les registres d'images Trident et CSI en miroir pour le mode hors ligne, activer les journaux de débogage ou spécifier les secrets d'extraction d'images.
. Installez Trident en utilisant le fichier YAML de bundle approprié à votre environnement, où _<bundle.yaml>_ est
`bundle_pre_1_25.yaml` ou `bundle_post_1_25.yaml` en fonction de votre version de Kubernetes. Par exemple, si vous installez Trident 25.06.0, exécutez la commande suivante :
+
[listing]
----
kubectl create -f 25.06.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. Modifiez le torc trident pour inclure l'image 25.06.0.




== Mettre à niveau une installation Helm

Vous pouvez mettre à niveau une installation de Trident Helm.


WARNING: Lors de la mise à niveau d'un cluster Kubernetes de la version 1.24 à la version 1.25 ou ultérieure sur lequel Trident est installé, vous devez mettre à jour le fichier values.yaml pour configurer `excludePodSecurityPolicy` à `true` ou ajouter `--set excludePodSecurityPolicy=true` au `helm upgrade` commande avant de pouvoir mettre à niveau le cluster.

Si vous avez déjà mis à niveau votre cluster Kubernetes de la version 1.24 à la version 1.25 sans mettre à niveau le helm Trident , la mise à niveau du helm échoue.  Pour que la mise à niveau du poste de pilotage puisse être effectuée, veuillez suivre les étapes préalables suivantes :

. Installez le plugin helm-mapkubeapis depuis https://github.com/helm/helm-mapkubeapis[] .
. Effectuez un test à blanc pour la version de Trident dans l'espace de noms où Trident est installé.  Cette liste répertorie les ressources qui seront nettoyées.
+
[listing]
----
helm mapkubeapis --dry-run trident  --namespace trident
----
. Effectuez une exécution complète avec Helm pour effectuer le nettoyage.
+
[listing]
----
helm mapkubeapis trident  --namespace trident
----


.Étapes
. Si tulink:../trident-get-started/kubernetes-deploy-helm.html#deploy-the-trident-operator-and-install-trident-using-helm["Trident a été installé à l'aide de Helm."] , vous pouvez utiliser `helm upgrade trident netapp-trident/trident-operator --version 100.2506.0` mettre à niveau en une seule étape.  Si vous n'avez pas ajouté le dépôt Helm ou si vous ne pouvez pas l'utiliser pour effectuer la mise à niveau :
+
.. Téléchargez la dernière version de Trident depuislink:https://github.com/NetApp/trident/releases/latest["la section _Assets_ sur GitHub"^] .
.. Utilisez le `helm upgrade` commande où `trident-operator-25.06.0.tgz` reflète la version vers laquelle vous souhaitez effectuer la mise à niveau.
+
[listing]
----
helm upgrade <name> trident-operator-25.06.0.tgz
----
+

NOTE: Si vous définissez des options personnalisées lors de l'installation initiale (comme la spécification de registres privés et en miroir pour les images Trident et CSI), ajoutez le `helm upgrade` commande utilisant `--set` afin de garantir que ces options soient incluses dans la commande de mise à niveau, sinon les valeurs seront réinitialisées à leurs valeurs par défaut.



. Courir `helm list` vérifier que la version du graphique et celle de l'application ont bien été mises à jour.  Courir `tridentctl logs` pour examiner les messages de débogage.




== Mise à niveau depuis un `tridentctl` installation à l'opérateur Trident

Vous pouvez mettre à jour l'opérateur Trident vers sa dernière version à partir d'un `tridentctl` installation.  Les backends et les PVC existants seront automatiquement disponibles.


NOTE: Avant de changer de méthode d'installation, consultezlink:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["Passer d'une méthode d'installation à une autre"] .

.Étapes
. Téléchargez la dernière version de Trident .
+
[listing]
----
# Download the release required [25.06.0]
mkdir 25.06.0
cd 25.06.0
wget https://github.com/NetApp/trident/releases/download/v25.06.0/trident-installer-25.06.0.tar.gz
tar -xf trident-installer-25.06.0.tar.gz
cd trident-installer
----
. Créez le `tridentorchestrator` CRD du manifeste.
+
[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
. Déployez l'opérateur à portée de cluster dans le même espace de noms.
+
[listing]
----
kubectl create -f deploy/<bundle-name.yaml>

serviceaccount/trident-operator created
clusterrole.rbac.authorization.k8s.io/trident-operator created
clusterrolebinding.rbac.authorization.k8s.io/trident-operator created
deployment.apps/trident-operator created
podsecuritypolicy.policy/tridentoperatorpods created

#Examine the pods in the Trident namespace
NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-79df798bdc-m79dc   6/6     Running   0          150d
trident-node-linux-xrst8              2/2     Running   0          150d
trident-operator-5574dbbc68-nthjv     1/1     Running   0          1m30s
----
. Créer un `TridentOrchestrator` CR pour l'installation de Trident.
+
[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident

kubectl create -f deploy/crds/tridentorchestrator_cr.yaml

#Examine the pods in the Trident namespace
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-79df798bdc-m79dc        6/6     Running   0          1m
trident-csi-xrst8                   2/2     Running   0          1m
trident-operator-5574dbbc68-nthjv   1/1     Running   0          5m41s
----
. Confirmez que Trident a bien été mis à niveau vers la version prévue.
+
[listing]
----
kubectl describe torc trident | grep Message -A 3

Message:                Trident installed
Namespace:              trident
Status:                 Installed
Version:                v25.06.0
----

