---
sidebar: sidebar 
permalink: trident-use/anf-examples.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows 
summary: Découvrez les options de configuration des serveurs NFS et SMB pour Azure NetApp Files et consultez des exemples de configuration. 
---
= Options et exemples de configuration du backend Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les options de configuration des serveurs NFS et SMB pour Azure NetApp Files et consultez des exemples de configuration.



== options de configuration du backend

Trident utilise votre configuration backend (sous-réseau, réseau virtuel, niveau de service et emplacement) pour créer des volumes Azure NetApp Files sur des pools de capacité disponibles à l'emplacement demandé et correspondant au niveau de service et au sous-réseau demandés.


NOTE: * À partir de la version NetApp Trident 25.06, les pools de capacité QoS manuels sont pris en charge en tant qu'aperçu technique.*

Les backends Azure NetApp Files offrent ces options de configuration.

[cols="3"]
|===
| Paramètre | Description | Défaut 


| `version` |  | Toujours 1 


| `storageDriverName` | Nom du pilote de stockage | "azure-netapp-files" 


| `backendName` | Nom personnalisé ou système de stockage | Nom du conducteur + "_" + caractères aléatoires 


| `subscriptionID` | L'ID d'abonnement de votre abonnement Azure (facultatif lorsque les identités gérées sont activées sur un cluster AKS). |  


| `tenantID` | L'identifiant du locataire issu d'un enregistrement d'application est facultatif lorsque des identités gérées ou une identité cloud sont utilisées sur un cluster AKS. |  


| `clientID` | L'identifiant client issu d'un enregistrement d'application est facultatif lorsque des identités gérées ou une identité cloud sont utilisées sur un cluster AKS. |  


| `clientSecret` | Le secret client issu d'un enregistrement d'application est facultatif lorsque des identités gérées ou une identité cloud sont utilisées sur un cluster AKS. |  


| `serviceLevel` | L'un des `Standard` , `Premium` , ou `Ultra` | "" (aléatoire) 


| `location` | Nom de l'emplacement Azure où les nouveaux volumes seront créés. Facultatif lorsque les identités gérées sont activées sur un cluster AKS. |  


| `resourceGroups` | Liste des groupes de ressources pour filtrer les ressources découvertes | "[]" (aucun filtre) 


| `netappAccounts` | Liste des comptes NetApp pour le filtrage des ressources découvertes | "[]" (aucun filtre) 


| `capacityPools` | Liste des pools de capacité pour le filtrage des ressources découvertes | "[]" (sans filtre, aléatoire) 


| `virtualNetwork` | Nom d'un réseau virtuel avec un sous-réseau délégué | "" 


| `subnet` | Nom d'un sous-réseau délégué à `Microsoft.Netapp/volumes` | "" 


| `networkFeatures` | Ensemble de fonctionnalités VNet pour un volume, peut être `Basic` ou `Standard` .  La fonctionnalité Réseau n'est pas disponible dans toutes les régions et peut nécessiter un abonnement pour être activée.  Spécifier `networkFeatures` Lorsque cette fonctionnalité n'est pas activée, le provisionnement des volumes échoue. | "" 


| `nfsMountOptions` | Contrôle précis des options de montage NFS.  Ignoré pour les volumes SMB.  Pour monter des volumes à l'aide de NFS version 4.1, incluez `nfsvers=4` dans la liste des options de montage séparées par des virgules, choisissez NFS v4.1.  Les options de montage définies dans une définition de classe de stockage remplacent les options de montage définies dans la configuration du backend. | "nfsvers=3" 


| `limitVolumeSize` | L'approvisionnement échouera si la taille du volume demandée est supérieure à cette valeur. | "" (non appliqué par défaut) 


| `debugTraceFlags` | Indicateurs de débogage à utiliser lors du dépannage.  Exemple, `\{"api": false, "method": true, "discovery": true}` .  N’utilisez cette fonction que si vous effectuez un dépannage et avez besoin d’un journal de transactions détaillé. | nul 


| `nasType` | Configurer la création de volumes NFS ou SMB.  Les options sont `nfs` , `smb` ou nul.  La valeur nulle correspond par défaut aux volumes NFS. | `nfs` 


| `supportedTopologies` | Représente une liste des régions et zones prises en charge par ce serveur.  Pour plus d'informations, veuillez consulterlink:../trident-use/csi-topology.html["Utiliser la topologie CSI"] . |  


| `qosType` | Indique le type de QoS : Auto ou Manuel. *Aperçu technique de Trident 25.06* | Automatique 


| `maxThroughput` | Définit le débit maximal autorisé en Mio/s. Prise en charge uniquement pour les pools de capacité QoS manuels. *Aperçu technique de Trident 25.06* | `4 MiB/sec` 
|===

NOTE: Pour plus d'informations sur les fonctionnalités réseau, consultezlink:https://docs.microsoft.com/en-us/azure/azure-netapp-files/configure-network-features["Configurer les fonctionnalités réseau pour un volume Azure NetApp Files"^] .



=== Autorisations et ressources requises

Si vous recevez une erreur « Aucun pool de capacité trouvé » lors de la création d'un PVC, il est probable que l'enregistrement de votre application ne dispose pas des autorisations et des ressources requises (sous-réseau, réseau virtuel, pool de capacité) associées.  Si le mode débogage est activé, Trident enregistrera les ressources Azure découvertes lors de la création du backend.  Vérifiez qu'un rôle approprié est utilisé.

Les valeurs pour `resourceGroups` , `netappAccounts` , `capacityPools` , `virtualNetwork` , et `subnet` peuvent être spécifiés à l'aide de noms courts ou complets.  Dans la plupart des situations, il est recommandé d'utiliser des noms complets, car les noms courts peuvent correspondre à plusieurs ressources portant le même nom.

Le `resourceGroups` , `netappAccounts` , et `capacityPools` Les valeurs sont des filtres qui limitent l'ensemble des ressources découvertes à celles disponibles pour ce système de stockage et peuvent être spécifiées dans n'importe quelle combinaison.  Les noms complets suivent ce format :

[cols="2"]
|===
| Type | Format 


| Groupe de ressources | <groupe de ressources> 


| Compte NetApp | <groupe de ressources>/<compte NetApp> 


| Pool de capacité | <groupe de ressources>/<compte NetApp>/<pool de capacité> 


| Réseau virtuel | <groupe de ressources>/<réseau virtuel> 


| Sous-réseau | <groupe de ressources>/<réseau virtuel>/<sous-réseau> 
|===


=== Provisionnement de volume

Vous pouvez contrôler le provisionnement des volumes par défaut en spécifiant les options suivantes dans une section spéciale du fichier de configuration. Se référer à <<Exemples de configurations>> pour plus de détails.

[cols=",,"]
|===
| Paramètre | Description | Défaut 


| `exportRule` | Règles d'exportation pour les nouveaux volumes. 
`exportRule` doit être une liste séparée par des virgules de toute combinaison d'adresses IPv4 ou de sous-réseaux IPv4 en notation CIDR.  Ignoré pour les volumes SMB. | "0.0.0.0/0" 


| `snapshotDir` | Contrôle la visibilité du répertoire .snapshot | « Vrai » pour NFSv4, « Faux » pour NFSv3 


| `size` | La taille par défaut des nouveaux volumes | "100G" 


| `unixPermissions` | Les permissions Unix des nouveaux volumes (4 chiffres octaux).  Ignoré pour les volumes SMB. | "" (fonctionnalité en avant-première, nécessite une inscription sur la liste blanche dans l'abonnement) 
|===


== Exemples de configurations

Les exemples suivants présentent des configurations de base qui laissent la plupart des paramètres par défaut.  Voici la manière la plus simple de définir un backend.

.Configuration minimale
[%collapsible]
====
Il s'agit de la configuration minimale absolue du backend.  Avec cette configuration, Trident détecte tous vos comptes NetApp , pools de capacité et sous-réseaux délégués à Azure NetApp Files dans l'emplacement configuré, et place les nouveaux volumes sur l'un de ces pools et sous-réseaux de manière aléatoire.  Parce que `nasType` est omis, le `nfs` La valeur par défaut s'applique et le système dorsal provisionnera les volumes NFS.

Cette configuration est idéale lorsque vous débutez avec Azure NetApp Files et que vous faites des essais, mais en pratique, vous souhaiterez définir une portée supplémentaire pour les volumes que vous provisionnez.

[source, yaml]
----
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-anf-1
  namespace: trident
spec:
  version: 1
  storageDriverName: azure-netapp-files
  subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
  tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
  clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
  clientSecret: SECRET
  location: eastus
----
====
.Gestion des identités pour AKS
[%collapsible]
====
Cette configuration backend omet `subscriptionID` , `tenantID` , `clientID` , et `clientSecret` , qui sont facultatives lors de l'utilisation d'identités gérées.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-anf-1
  namespace: trident
spec:
  version: 1
  storageDriverName: azure-netapp-files
  capacityPools:
    - ultra-pool
  resourceGroups:
    - aks-ami-eastus-rg
  netappAccounts:
    - smb-na
  virtualNetwork: eastus-prod-vnet
  subnet: eastus-anf-subnet
----
====
.Identité cloud pour AKS
[%collapsible]
====
Cette configuration backend omet `tenantID` , `clientID` , et `clientSecret` , qui sont facultatives lors de l'utilisation d'une identité cloud.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-anf-1
  namespace: trident
spec:
  version: 1
  storageDriverName: azure-netapp-files
  capacityPools:
    - ultra-pool
  resourceGroups:
    - aks-ami-eastus-rg
  netappAccounts:
    - smb-na
  virtualNetwork: eastus-prod-vnet
  subnet: eastus-anf-subnet
  location: eastus
  subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
----
====
.Configuration spécifique du niveau de service avec filtres de pool de capacité
[%collapsible]
====
Cette configuration backend place les volumes dans Azure. `eastus` emplacement dans un `Ultra` réserve de capacité.  Trident détecte automatiquement tous les sous-réseaux délégués à Azure NetApp Files à cet emplacement et place un nouveau volume sur l'un d'eux de manière aléatoire.

[source, yaml]
----
---
version: 1
storageDriverName: azure-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
serviceLevel: Ultra
capacityPools:
  - application-group-1/account-1/ultra-1
  - application-group-1/account-1/ultra-2
----
====
.Exemple de backend avec pools de capacité QoS manuels
[%collapsible]
====
Cette configuration backend place les volumes dans Azure. `eastus` emplacement avec pools de capacité QoS manuels. *Aperçu technique dans NetApp Trident 25.06*.

[source, yaml]
----
---
version: 1
storageDriverName: azure-netapp-files
backendName: anf1
location: eastus
labels:
  clusterName: test-cluster-1
  cloud: anf
  nasType: nfs
defaults:
  qosType: Manual
storage:
  - serviceLevel: Ultra
    labels:
      performance: gold
    defaults:
      maxThroughput: 10
  - serviceLevel: Premium
    labels:
      performance: silver
    defaults:
      maxThroughput: 5
  - serviceLevel: Standard
    labels:
      performance: bronze
    defaults:
      maxThroughput: 3
----
====
.Configuration avancée
[%collapsible]
====
Cette configuration backend réduit encore la portée du placement des volumes à un seul sous-réseau et modifie également certains paramètres par défaut de provisionnement des volumes.

[source, yaml]
----
---
version: 1
storageDriverName: azure-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
serviceLevel: Ultra
capacityPools:
  - application-group-1/account-1/ultra-1
  - application-group-1/account-1/ultra-2
virtualNetwork: my-virtual-network
subnet: my-subnet
networkFeatures: Standard
nfsMountOptions: vers=3,proto=tcp,timeo=600
limitVolumeSize: 500Gi
defaults:
  exportRule: 10.0.0.0/24,10.0.1.0/24,10.0.2.100
  snapshotDir: "true"
  size: 200Gi
  unixPermissions: "0777"

----
====
.Configuration du pool virtuel
[%collapsible]
====
Cette configuration backend définit plusieurs pools de stockage dans un seul fichier.  Ceci est utile lorsque vous disposez de plusieurs pools de capacité prenant en charge différents niveaux de service et que vous souhaitez créer des classes de stockage dans Kubernetes qui les représentent.  Des étiquettes virtuelles ont été utilisées pour différencier les bassins en fonction de `performance` .

[source, yaml]
----
---
version: 1
storageDriverName: azure-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
resourceGroups:
  - application-group-1
networkFeatures: Basic
nfsMountOptions: vers=3,proto=tcp,timeo=600
labels:
  cloud: azure
storage:
  - labels:
      performance: gold
    serviceLevel: Ultra
    capacityPools:
      - ultra-1
      - ultra-2
    networkFeatures: Standard
  - labels:
      performance: silver
    serviceLevel: Premium
    capacityPools:
      - premium-1
  - labels:
      performance: bronze
    serviceLevel: Standard
    capacityPools:
      - standard-1
      - standard-2

----
====
.Configuration des topologies prises en charge
[%collapsible]
====
Trident facilite la mise à disposition de volumes pour les charges de travail en fonction des régions et des zones de disponibilité.  Le `supportedTopologies` Dans cette configuration backend, le bloc `block` sert à fournir une liste de régions et de zones par backend.  Les valeurs de région et de zone spécifiées ici doivent correspondre aux valeurs de région et de zone des étiquettes de chaque nœud du cluster Kubernetes.  Ces régions et zones représentent la liste des valeurs autorisées qui peuvent être fournies dans une classe de stockage.  Pour les classes de stockage qui contiennent un sous-ensemble des régions et zones fournies dans un backend, Trident crée des volumes dans la région et la zone mentionnées.  Pour plus d'informations, veuillez consulterlink:../trident-use/csi-topology.html["Utiliser la topologie CSI"] .

[source, yaml]
----
---
version: 1
storageDriverName: azure-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
serviceLevel: Ultra
capacityPools:
  - application-group-1/account-1/ultra-1
  - application-group-1/account-1/ultra-2
supportedTopologies:
  - topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-1
  - topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-2
----
====


== Définitions des classes de stockage

Ce qui suit `StorageClass` Les définitions font référence aux pools de stockage ci-dessus.



=== Exemples de définitions utilisant `parameter.selector` champ

En utilisant `parameter.selector` vous pouvez spécifier pour chaque `StorageClass` le pool virtuel utilisé pour héberger un volume.  Le volume comprendra les aspects définis dans le pool choisi.

[source, yaml]
----
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=gold
allowVolumeExpansion: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: silver
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=silver
allowVolumeExpansion: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bronze
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=bronze
allowVolumeExpansion: true
----


=== Exemples de définitions pour les volumes SMB

En utilisant `nasType` , `node-stage-secret-name` , et `node-stage-secret-namespace` Vous pouvez spécifier un volume SMB et fournir les informations d'identification Active Directory requises.

.Configuration de base sur l'espace de noms par défaut
[%collapsible]
====
[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: anf-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "azure-netapp-files"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
----
====
.Utilisation de secrets différents par espace de noms
[%collapsible]
====
[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: anf-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "azure-netapp-files"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
----
====
.Utiliser différents secrets par volume
[%collapsible]
====
[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: anf-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "azure-netapp-files"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
----
====

NOTE: `nasType: smb`filtres pour les pools prenant en charge les volumes SMB. `nasType: nfs` ou `nasType: null` Filtres pour les pools NFS.



== Créer le backend

Après avoir créé le fichier de configuration du backend, exécutez la commande suivante :

[listing]
----
tridentctl create backend -f <backend-file>
----
Si la création du backend échoue, c'est qu'il y a un problème avec la configuration du backend.  Vous pouvez consulter les journaux pour déterminer la cause en exécutant la commande suivante :

[listing]
----
tridentctl logs
----
Une fois le problème du fichier de configuration identifié et corrigé, vous pouvez exécuter à nouveau la commande de création.
