---
sidebar: sidebar 
permalink: trident-use/backend_ops_kubectl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, create backends, delete backends, update backends, view backends 
summary: 'Découvrez comment effectuer des opérations de gestion du backend en utilisant `kubectl` .' 
---
= Effectuez la gestion du backend avec kubectl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment effectuer des opérations de gestion du backend en utilisant `kubectl` .



== Supprimer un backend

En supprimant un `TridentBackendConfig` , vous demandez à Trident de supprimer/conserver les backends (en fonction de `deletionPolicy` ).  Pour supprimer un backend, assurez-vous que `deletionPolicy` est configuré pour être supprimé.  Pour supprimer uniquement le `TridentBackendConfig` , assurez-vous que `deletionPolicy` est prévu pour conserver.  Cela garantit que le système dorsal est toujours présent et peut être géré à l'aide de `tridentctl` .

Exécutez la commande suivante :

[listing]
----
kubectl delete tbc <tbc-name> -n trident
----
Trident ne supprime pas les secrets Kubernetes qui étaient utilisés par `TridentBackendConfig` .  L'utilisateur Kubernetes est responsable du nettoyage des secrets.  Il convient d'être prudent lors de la suppression de secrets.  Vous ne devez supprimer les secrets que s'ils ne sont pas utilisés par les systèmes backend.



== Afficher les backends existants

Exécutez la commande suivante :

[listing]
----
kubectl get tbc -n trident
----
Vous pouvez également courir `tridentctl get backend -n trident` ou `tridentctl get backend -o yaml -n trident` pour obtenir la liste de tous les serveurs backend existants.  Cette liste inclura également les backends créés avec `tridentctl` .



== Mettre à jour un backend

Il peut exister plusieurs raisons de mettre à jour un backend :

* Les identifiants d'accès au système de stockage ont changé.  Pour mettre à jour les informations d'identification, le secret Kubernetes utilisé dans le `TridentBackendConfig` L'objet doit être mis à jour.  Trident mettra automatiquement à jour le système dorsal avec les dernières informations d'identification fournies.  Exécutez la commande suivante pour mettre à jour le secret Kubernetes :
+
[listing]
----
kubectl apply -f <updated-secret-file.yaml> -n trident
----
* Les paramètres (tels que le nom de la SVM ONTAP utilisée) doivent être mis à jour.
+
** Vous pouvez mettre à jour `TridentBackendConfig` objets directement via Kubernetes à l'aide de la commande suivante :
+
[listing]
----
kubectl apply -f <updated-backend-file.yaml>
----
** Vous pouvez également apporter des modifications à l'existant `TridentBackendConfig` CR en utilisant la commande suivante :
+
[listing]
----
kubectl edit tbc <tbc-name> -n trident
----




[NOTE]
====
* En cas d'échec d'une mise à jour du système dorsal, celui-ci reste dans sa dernière configuration connue.  Vous pouvez consulter les journaux pour déterminer la cause en exécutant la commande suivante : `kubectl get tbc <tbc-name> -o yaml -n trident` ou `kubectl describe tbc <tbc-name> -n trident` .
* Une fois le problème du fichier de configuration identifié et corrigé, vous pouvez relancer la commande de mise à jour.


====