---
sidebar: sidebar 
permalink: trident-use/manage-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: Vous pouvez consulter les classes de stockage existantes, définir une classe de stockage par défaut, identifier le système de stockage dorsal et supprimer des classes de stockage. 
---
= Gérer les classes de stockage
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez consulter les classes de stockage existantes, définir une classe de stockage par défaut, identifier le système de stockage dorsal et supprimer des classes de stockage.



== Afficher les classes de stockage existantes

* Pour afficher les classes de stockage Kubernetes existantes, exécutez la commande suivante :


[listing]
----
kubectl get storageclass
----
* Pour afficher les détails d'une classe de stockage Kubernetes, exécutez la commande suivante :


[listing]
----
kubectl get storageclass <storage-class> -o json
----
* Pour afficher les classes de stockage synchronisées de Trident, exécutez la commande suivante :


[listing]
----
tridentctl get storageclass
----
* Pour afficher les détails de la classe de stockage synchronisée de Trident, exécutez la commande suivante :


[listing]
----
tridentctl get storageclass <storage-class> -o json
----


== Définir une classe de stockage par défaut

Kubernetes 1.6 a ajouté la possibilité de définir une classe de stockage par défaut.  Il s'agit de la classe de stockage qui sera utilisée pour provisionner un volume persistant si un utilisateur n'en spécifie pas un dans une revendication de volume persistant (PVC).

* Définissez une classe de stockage par défaut en configurant l'annotation `storageclass.kubernetes.io/is-default-class` à vrai dans la définition de la classe de stockage.  Conformément aux spécifications, toute autre valeur ou absence d'annotation est interprétée comme fausse.
* Vous pouvez configurer une classe de stockage existante comme classe de stockage par défaut à l'aide de la commande suivante :


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
* De même, vous pouvez supprimer l'annotation de classe de stockage par défaut en utilisant la commande suivante :


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
On trouve également des exemples dans le package d'installation de Trident qui incluent cette annotation.


NOTE: Il ne devrait y avoir qu'une seule classe de stockage par défaut dans votre cluster à la fois.  Techniquement, Kubernetes ne vous empêche pas d'en avoir plusieurs, mais il se comportera comme s'il n'existait aucune classe de stockage par défaut.



== Identifier le backend d'une classe de stockage

Voici un exemple du type de questions auxquelles vous pouvez répondre avec le JSON. `tridentctl` Sorties pour les objets backend Trident .  Cela utilise le `jq` utilitaire, que vous devrez peut-être installer au préalable.

[listing]
----
tridentctl get storageclass -o json | jq  '[.items[] | {storageClass: .Config.name, backends: [.storage]|unique}]'
----


== Supprimer une classe de stockage

Pour supprimer une classe de stockage de Kubernetes, exécutez la commande suivante :

[listing]
----
kubectl delete storageclass <storage-class>
----
`<storage-class>`devrait être remplacé par votre classe de stockage.

Tous les volumes persistants créés via cette classe de stockage resteront intacts et Trident continuera de les gérer.


NOTE: Trident impose un blanc `fsType` pour les volumes qu'elle génère.  Pour les backends iSCSI, il est recommandé d'appliquer `parameters.fsType` dans la classe de stockage.  Vous devez supprimer les StorageClasses existantes et les recréer avec `parameters.fsType` spécifié.
