---
sidebar: sidebar 
permalink: trident-use/vol-provision.html 
keywords: volumes, pvc, pv, persistentvolume, persistentvolumeclaim, mount, pod, provision 
summary: 'Créez un PersistentVolume (PV) et un PersistentVolumeClaim (PVC) qui utilise la classe de stockage Kubernetes configurée pour demander l"accès au PV.  Vous pouvez ensuite monter le panneau photovoltaïque sur un support.' 
---
= Provisionnez un volume
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Créez une PersistentVolumeClaim (PVC) qui utilise la StorageClass Kubernetes configurée pour demander l'accès au PV.  Vous pouvez ensuite monter le panneau photovoltaïque sur un support.



== Aperçu

UN https://kubernetes.io/docs/concepts/storage/persistent-volumes["_PersistentVolumeClaim_"^] (PVC) est une demande d'accès au PersistentVolume sur le cluster.

Le PVC peut être configuré pour demander un stockage d'une certaine taille ou un certain mode d'accès.  En utilisant la StorageClass associée, l'administrateur du cluster peut contrôler bien plus que la taille et le mode d'accès du PersistentVolume, comme par exemple les performances ou le niveau de service.

Une fois le PVC créé, vous pouvez monter le volume dans un boîtier.



== Créer le PVC

.Étapes
. Créez le PVC.
+
[listing]
----
kubectl create -f pvc.yaml
----
. Vérifier l'état du PVC.
+
[listing]
----
kubectl get pvc
----


[listing]
----
NAME        STATUS  VOLUME     CAPACITY   ACCESS MODES  STORAGECLASS AGE
pvc-storage Bound   pv-name    1Gi        RWO                  5m
----
. Montez le volume dans un boîtier.
+
[listing]
----
kubectl create -f pv-pod.yaml
----
+

NOTE: Vous pouvez suivre les progrès en utilisant `kubectl get pod --watch` .

. Vérifiez que le volume est monté sur `/my/mount/path` .
+
[listing]
----
kubectl exec -it task-pv-pod -- df -h /my/mount/path
----
. Vous pouvez maintenant supprimer le Pod.  L'application Pod n'existera plus, mais le volume restera.
+
[listing]
----
kubectl delete pod pv-pod
----




=== Exemples de manifestes

.Manifestes d'exemple de PersistentVolumeClaim
[%collapsible]
====
Ces exemples illustrent les options de configuration de base pour les installations en PVC.

.PVC avec accès RWO
Cet exemple montre un PVC de base avec accès RWO associé à une StorageClass nommée `basic-csi` .

[source, yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
.PVC avec NVMe/TCP
Cet exemple montre un PVC de base pour NVMe/TCP avec accès RWO associé à une StorageClass nommée `protection-gold` .

[source, yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san-nvme
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 300Mi
storageClassName: protection-gold
----
====
.Exemples de manifestes Pod
[%collapsible]
====
Ces exemples illustrent des configurations de base pour fixer le PVC à un support.

.configuration de base
[source, yaml]
----
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
       claimName: pvc-storage
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: storage
----
.Configuration NVMe/TCP de base
[source, yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  volumes:
    - name: basic-pvc
      persistentVolumeClaim:
        claimName: pvc-san-nvme
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: basic-pvc
----
====
Se référer àlink:../trident-reference/objects.html["Objets Kubernetes et Trident"] pour plus de détails sur la manière dont les classes de stockage interagissent avec le `PersistentVolumeClaim` et des paramètres permettant de contrôler les volumes de provisionnement de Trident .
