---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, Trident, methods, operator, tridentctl, helm, attributes, customize 
summary: 'Vous pouvez utiliser le programme d"installation de Trident pour personnaliser le déploiement.' 
---
= Personnaliser l'installation de tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le programme d'installation Trident pour personnaliser l'installation.



== Découvrez l'installateur

Le programme d'installation de Trident vous permet de personnaliser les attributs.  Par exemple, si vous avez copié l'image Trident dans un dépôt privé, vous pouvez spécifier le nom de l'image en utilisant `--trident-image` .  Si vous avez copié l'image Trident ainsi que les images CSI sidecar nécessaires dans un dépôt privé, il peut être préférable de spécifier l'emplacement de ce dépôt en utilisant le `--image-registry` interrupteur, qui prend la forme `<registry FQDN>[:port]` .


IMPORTANT: Lors de l'installation de Trident dans un dépôt privé, si vous utilisez le `--image-registry` Utilisez l'option permettant de spécifier l'emplacement du dépôt, ne pas utiliser `/netapp/` dans le chemin du dépôt. Par exemple: `./tridentctl install --image-registry <image-registry> -n <namespace>`

Si vous utilisez une distribution Kubernetes, où `kubelet` conserve ses données sur un chemin autre que le chemin habituel `/var/lib/kubelet` , vous pouvez spécifier le chemin alternatif en utilisant `--kubelet-dir` .

Si vous devez personnaliser l'installation au-delà de ce que permettent les arguments du programme d'installation, vous pouvez également personnaliser les fichiers de déploiement.  En utilisant le `--generate-custom-yaml` Ce paramètre crée les fichiers YAML suivants dans le répertoire d'installation : `setup` annuaire:

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml`


Une fois ces fichiers générés, vous pouvez les modifier selon vos besoins, puis les utiliser. `--use-custom-yaml` pour installer votre déploiement personnalisé.

[source, console]
----
./tridentctl install -n trident --use-custom-yaml
----