= annotation de délai d'expiration du déplaceur de données
:allow-uri-read: 




== annotation de délai d'expiration du déplaceur de données

Lors des opérations de sauvegarde et de restauration, vous pouvez utiliser l'annotation `protect.trident.netapp.io/data-mover-timeout-sec` configurer le délai d'expiration des opérations de déplacement de données.  Cette annotation spécifie la durée maximale, en secondes, pendant laquelle un déplaceur de données doit attendre la fin d'une opération spécifique avant d'expirer.  Il est particulièrement utile dans les situations où des problèmes de réseau ou d'autres facteurs peuvent entraîner l'arrêt des opérations de transfert de données.  Cela permet de détecter et de gérer les opérations bloquées, plutôt que de définir un délai d'expiration général pour l'ensemble du processus.  Par exemple, si aucune progression n'est constatée lors de la restauration des données de volume en raison de problèmes de réseau, l'opération expirera après la durée spécifiée.

Vous pouvez utiliser cette annotation dans votre fichier YAML comme indiqué ci-dessous :

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
Dans cet exemple, l'annotation échoue. `BackupRestore` Opération interrompue si aucune progression n'est constatée dans les 2 secondes suivant l'opération de restauration.


NOTE: Si la valeur de l'annotation est inférieure ou égale à 0, l'opération échouera immédiatement.
