---
sidebar: sidebar 
permalink: trident-get-started/k8s-netapp.html 
keywords: kubernetes, netapp storage, ontap, cloud volumes ontap, santricity, element software, netapp hci, anf, azure netapp files, cloud volumes service for google cloud, gcp, aws, amazon fsx 
summary: 'La gamme de produits de stockage NetApp s"intègre à de nombreux aspects d"un cluster Kubernetes, offrant des capacités avancées de gestion des données qui améliorent la fonctionnalité, les capacités, les performances et la disponibilité du déploiement Kubernetes.' 
---
= Intégration de Kubernetes avec les produits NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La gamme de produits de stockage NetApp s'intègre à de nombreux aspects d'un cluster Kubernetes, offrant des capacités avancées de gestion des données qui améliorent la fonctionnalité, les capacités, les performances et la disponibilité du déploiement Kubernetes.



== Trident

https://docs.netapp.com/us-en/trident/["Trident"^]facilite la gestion, la protection et le déplacement des charges de travail conteneurisées riches en données exécutées sur Kubernetes, au sein et entre les clouds publics et sur site.  Trident fournit et provisionne un stockage de conteneurs persistant en utilisant Trident, issu du portefeuille de stockage NetApp éprouvé et étendu, dans le cloud public et sur site.  Il offre également un ensemble complet de fonctionnalités avancées de gestion des données adaptées aux applications, telles que la création d'instantanés, la sauvegarde et la restauration, les journaux d'activité et le clonage actif pour la protection des données, la récupération après sinistre/de données, l'audit des données et les cas d'utilisation de migration pour les charges de travail Kubernetes.



== ONTAP

ONTAP est le système d'exploitation de stockage multiprotocole et unifié de NetApp qui offre des fonctionnalités avancées de gestion des données pour toutes les applications.  Les systèmes ONTAP proposent des configurations entièrement flash, hybrides ou entièrement HDD et offrent de nombreux modèles de déploiement différents, notamment du matériel conçu sur mesure (FAS et AFF), des solutions « white-box » (ONTAP Select) et des solutions exclusivement cloud (Cloud Volumes ONTAP).


NOTE: Trident prend en charge tous les modèles de déploiement ONTAP mentionnés ci-dessus.



== Cloud Volumes ONTAP

http://cloud.netapp.com/ontap-cloud?utm_source=GitHub&utm_campaign=Trident["Cloud Volumes ONTAP"^]est un dispositif de stockage exclusivement logiciel qui exécute le logiciel de gestion de données ONTAP dans le cloud.  Vous pouvez utiliser Cloud Volumes ONTAP pour les charges de travail de production, la reprise après sinistre, le DevOps, le partage de fichiers et la gestion de bases de données.  Il étend le stockage d'entreprise au cloud en offrant des gains d'efficacité en matière de stockage, une haute disponibilité, la réplication des données, la hiérarchisation des données et la cohérence des applications.



== Amazon FSx for NetApp ONTAP

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^]est un service AWS entièrement géré qui vous permet de lancer et d'exécuter des systèmes de fichiers alimentés par le système d'exploitation de stockage NetApp ONTAP .  FSx for ONTAP vous permet de tirer parti des fonctionnalités, des performances et des capacités d'administration de NetApp que vous connaissez, tout en bénéficiant de la simplicité, de l'agilité, de la sécurité et de l'évolutivité du stockage des données sur AWS.  FSx pour ONTAP prend en charge de nombreuses fonctionnalités du système de fichiers ONTAP et des API d'administration.



== Logiciel Element

https://www.netapp.com/data-management/element-software/["Élément"^]permet à l'administrateur de stockage de consolider les charges de travail en garantissant les performances et en permettant une empreinte de stockage simplifiée et rationalisée.  Associé à une API permettant d'automatiser tous les aspects de la gestion du stockage, Element permet aux administrateurs de stockage d'en faire plus avec moins d'efforts.



== NetApp HCI

https://www.netapp.com/virtual-desktop-infrastructure/netapp-hci/["NetApp HCI"^]simplifie la gestion et l'évolution du centre de données en automatisant les tâches de routine et en permettant aux administrateurs d'infrastructure de se concentrer sur des fonctions plus importantes.

L'infrastructure NetApp HCI est entièrement prise en charge par Trident.  Trident peut provisionner et gérer des périphériques de stockage pour les applications conteneurisées directement sur la plateforme de stockage NetApp HCI sous-jacente.



== Azure NetApp Files

https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^]est un service de partage de fichiers Azure de niveau entreprise, optimisé par NetApp.  Vous pouvez exécuter vos charges de travail basées sur des fichiers les plus exigeantes dans Azure de manière native, avec les performances et la gestion des données riches que vous attendez de NetApp.



== Google Cloud NetApp Volumes

https://cloud.netapp.com/cloud-volumes-service-for-gcp?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^]est un service de fichiers natif du cloud qui fournit des volumes NAS via NFS avec des performances 100 % flash.  Ce service permet d'exécuter n'importe quelle charge de travail, y compris les applications existantes, dans le cloud GCP.  Il fournit un service entièrement géré qui offre des performances élevées et constantes, un clonage instantané, une protection des données et un accès sécurisé aux instances Google Compute Engine (GCE).
