---
sidebar: sidebar 
permalink: trident-concepts/vol-access-groups.html 
keywords: volume access groups, element, solidfire, chap, Trident, hci, netapp hci, storage system, access volumes, 
summary: 'Découvrez comment Trident utilise les groupes d"accès aux volumes.' 
---
= groupes d'accès au volume
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Apprenez-en davantage sur la façon dont Trident utilise https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["groupes d'accès au volume"^] .


NOTE: Ignorez cette section si vous utilisez CHAP, ce qui est recommandé pour simplifier la gestion et éviter la limite de mise à l'échelle décrite ci-dessous.  De plus, si vous utilisez Trident en mode CSI, vous pouvez ignorer cette section.  Trident utilise CHAP lorsqu'il est installé en tant que fournisseur CSI amélioré.



== Découvrez les groupes d'accès au volume

Trident peut utiliser des groupes d'accès aux volumes pour contrôler l'accès aux volumes qu'il provisionne.  Si CHAP est désactivé, il s'attend à trouver un groupe d'accès appelé `trident` sauf si vous spécifiez un ou plusieurs ID de groupe d'accès dans la configuration.

Bien que Trident associe les nouveaux volumes aux groupes d'accès configurés, il ne crée ni ne gère les groupes d'accès eux-mêmes.  Les groupes d'accès doivent exister avant que le système de stockage dorsal ne soit ajouté à Trident, et ils doivent contenir les IQN iSCSI de chaque nœud du cluster Kubernetes qui pourrait potentiellement monter les volumes provisionnés par ce système dorsal.  Dans la plupart des installations, cela inclut chaque nœud de travail du cluster.

Pour les clusters Kubernetes comportant plus de 64 nœuds, il est recommandé d'utiliser plusieurs groupes d'accès.  Chaque groupe d'accès peut contenir jusqu'à 64 IQN, et chaque volume peut appartenir à quatre groupes d'accès.  Avec un maximum de quatre groupes d'accès configurés, n'importe quel nœud d'un cluster pouvant compter jusqu'à 256 nœuds pourra accéder à n'importe quel volume.  Pour connaître les dernières limites applicables aux groupes d'accès au volume, veuillez consulter : https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["ici"^] .

Si vous modifiez la configuration à partir d'une configuration utilisant la configuration par défaut `trident` groupe d'accès à un autre qui utilise également d'autres groupes, incluez l'ID du groupe d'accès. `trident` groupe d'accès dans la liste.
