---
sidebar: sidebar 
permalink: trident-reco/backup.html 
keywords: data protection, replication, dr, disaster recovery, snapmirror, back up, snapshot, element, volume replication 
summary: 'Découvrez les options de protection et de récupération pour Trident et les volumes créés avec Trident.  Vous devez disposer d"une stratégie de protection et de récupération des données pour chaque application ayant une exigence de persistance.' 
---
= Protection des données et reprise après sinistre
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les options de protection et de récupération pour Trident et les volumes créés avec Trident.  Vous devez disposer d'une stratégie de protection et de récupération des données pour chaque application ayant une exigence de persistance.



== Réplication et récupération du Trident

Vous pouvez créer une sauvegarde pour restaurer Trident en cas de sinistre.



=== Réplication du Trident

Trident utilise les CRD Kubernetes pour stocker et gérer son propre état et le cluster Kubernetes etcd pour stocker ses métadonnées.

.Étapes
. Sauvegardez le cluster Kubernetes etcd à l'aide delink:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster["Kubernetes : Sauvegarde d'un cluster etcd"^] .
. Placez les artefacts de sauvegarde sur un FlexVol volume
+

NOTE: NetApp recommande de protéger le SVM sur lequel réside le FlexVol par une relation SnapMirror avec un autre SVM.





=== Récupération de Trident

En utilisant les CRD Kubernetes et l'instantané etcd du cluster Kubernetes, vous pouvez récupérer Trident.

.Étapes
. Depuis la SVM de destination, montez le volume contenant les fichiers de données et les certificats etcd de Kubernetes sur l'hôte qui sera configuré comme nœud maître.
. Copiez tous les certificats requis relatifs au cluster Kubernetes sous `/etc/kubernetes/pki` et les fichiers membres etcd sous `/var/lib/etcd` .
. Restaurez le cluster Kubernetes à partir de la sauvegarde etcd en utilisantlink:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster["Kubernetes : Restauration d'un cluster etcd"^] .
. Courir `kubectl get crd` vérifier que toutes les ressources personnalisées Trident sont opérationnelles et récupérer les objets Trident pour vérifier que toutes les données sont disponibles.




== Réplication et récupération SVM

Trident ne permet pas de configurer les relations de réplication ; toutefois, l’administrateur de stockage peut utiliser https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html["ONTAP SnapMirror"^] pour répliquer une SVM.

En cas de sinistre, vous pouvez activer le SVM de destination SnapMirror pour commencer à diffuser des données.  Vous pourrez revenir au système principal une fois les systèmes restaurés.

.À propos de cette tâche
Tenez compte des points suivants lors de l'utilisation de la fonctionnalité de réplication SVM de SnapMirror :

* Vous devez créer un backend distinct pour chaque SVM avec SVM-DR activé.
* Configurez les classes de stockage pour sélectionner les backends répliqués uniquement lorsque cela est nécessaire afin d'éviter que des volumes qui n'ont pas besoin d'être répliqués soient provisionnés sur les backends qui prennent en charge SVM-DR.
* Les administrateurs d'applications doivent prendre en compte les coûts et la complexité supplémentaires liés à la réplication et examiner attentivement leur plan de reprise d'activité avant d'entamer ce processus.




=== Réplication SVM

Vous pouvez utiliserlink:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-workflow-concept.html["ONTAP: Réplication SnapMirror SVM"^] pour créer la relation de réplication SVM.

SnapMirror vous permet de définir des options pour contrôler ce qui doit être répliqué.  Vous devrez savoir quelles options vous avez sélectionnées lors de l'exécution.<<Récupération SVM à l'aide de Trident>> .

* link:https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html["-identité-préserver vrai"^]réplique l'intégralité de la configuration SVM.
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-lifs-svm-replication-task.html["-discard-configs réseau"^]Exclut les LIF et les paramètres réseau associés.
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-network-name-service-svm-replication-task.html["-identité-préserver faux"^]Réplique uniquement les volumes et la configuration de sécurité.




=== Récupération SVM à l'aide de Trident

Trident ne détecte pas automatiquement les défaillances des SVM.  En cas de sinistre, l'administrateur peut lancer manuellement le basculement Trident vers la nouvelle SVM.

.Étapes
. Annulez les transferts SnapMirror planifiés et en cours, interrompez la relation de réplication, arrêtez le SVM source puis activez le SVM de destination SnapMirror .
. Si vous avez spécifié `-identity-preserve false` ou `-discard-config network` Lors de la configuration de votre réplication SVM, mettez à jour le `managementLIF` et `dataLIF` dans le fichier de définition du backend Trident .
. Confirmer `storagePrefix` est présent dans le fichier de définition du backend Trident .  Ce paramètre ne peut pas être modifié.  Omission `storagePrefix` provoquera l'échec de la mise à jour du serveur.
. Mettez à jour tous les serveurs d'arrière-plan requis pour refléter le nouveau nom de la SVM de destination en utilisant :
+
[listing]
----
./tridentctl update backend <backend-name> -f <backend-json-file> -n <namespace>
----
. Si vous avez spécifié `-identity-preserve false` ou `discard-config network` Vous devez redémarrer tous les pods de l'application.
+

NOTE: Si vous avez spécifié `-identity-preserve true` , tous les volumes provisionnés par Trident commencent à diffuser des données lorsque le SVM de destination est activé.





== Réplication et récupération de volume

Trident ne peut pas configurer les relations de réplication SnapMirror ; toutefois, l’administrateur de stockage peut utiliserlink:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Réplication et récupération ONTAP SnapMirror"^] pour répliquer les volumes créés par Trident.

Vous pouvez ensuite importer les volumes récupérés dans Trident en utilisantlink:../trident-use/vol-import.html["importation de volume tridentctl"] .


NOTE: L'importation n'est pas prise en charge sur `ontap-nas-economy` , `ontap-san-economy` , ou `ontap-flexgroup-economy` conducteurs.



== Protection des données instantanées

Vous pouvez protéger et restaurer vos données à l'aide de :

* Un contrôleur de snapshots externe et des CRD pour créer des snapshots de volumes persistants (PV) Kubernetes.
+
link:../trident-use/vol-snapshots.html["Instantanés de volume"]

* Les snapshots ONTAP permettent de restaurer l'intégralité du contenu d'un volume ou de récupérer des fichiers ou des LUN individuels.
+
link:https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["Instantanés ONTAP"^]


