---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: 'Commencez par vérifier l"état de préparation de votre environnement opérationnel, de vos clusters d"applications, de vos applications et de vos licences. Assurez-vous que votre environnement répond à ces exigences pour déployer et utiliser Trident Protect.' 
---
= Exigences de Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Commencez par vérifier l'état de préparation de votre environnement opérationnel, de vos clusters d'applications, de vos applications et de vos licences. Assurez-vous que votre environnement répond à ces exigences pour déployer et utiliser Trident Protect.



== Compatibilité avec les clusters Kubernetes de Trident Protect

Trident Protect est compatible avec une large gamme d'offres Kubernetes entièrement gérées et autogérées, notamment :

* Amazon Elastic Kubernetes Service (EKS)
* Moteur Google Kubernetes (GKE)
* Service Kubernetes Microsoft Azure (AKS)
* Red Hat OpenShift
* SUSE Rancher
* Portefeuille VMware Tanzu
* Kubernetes en amont


[NOTE]
====
* Les sauvegardes Trident Protect sont prises en charge uniquement sur les nœuds de calcul Linux. Les nœuds de calcul Windows ne sont pas pris en charge pour les opérations de sauvegarde.
* Assurez-vous que le cluster sur lequel vous installez Trident Protect est configuré avec un contrôleur de snapshots en cours d'exécution et les CRD associés. Pour installer un contrôleur de snapshots, reportez-vous à la documentation. https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["ces instructions"] .


====


== Compatibilité du système de stockage Trident Protect

Trident Protect prend en charge les systèmes de stockage suivants :

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP
* baies de stockage ONTAP
* Google Cloud NetApp Volumes
* Azure NetApp Files


Assurez-vous que votre système de stockage réponde aux exigences suivantes :

* Assurez-vous que le stockage NetApp connecté au cluster utilise Trident 24.02 ou une version plus récente (Trident 24.10 est recommandé).


* Assurez-vous de disposer d'un système de stockage NetApp ONTAP .
* Assurez-vous d'avoir configuré un compartiment de stockage d'objets pour stocker les sauvegardes.
* Créez les espaces de noms d'application que vous prévoyez d'utiliser pour les applications ou les opérations de gestion des données d'application. Trident Protect ne crée pas ces espaces de noms pour vous ; si vous spécifiez un espace de noms inexistant dans une ressource personnalisée, l’opération échouera.




== Exigences pour les volumes de l'économie NAS

Trident Protect prend en charge les opérations de sauvegarde et de restauration sur les volumes NAS économiques. Les snapshots, les clones et la réplication SnapMirror vers des volumes nas-economy ne sont actuellement pas pris en charge. Vous devez activer un répertoire de snapshots pour chaque volume nas-economy que vous prévoyez d'utiliser avec Trident Protect.

[NOTE]
====
Certaines applications ne sont pas compatibles avec les volumes qui utilisent un répertoire de snapshots.  Pour ces applications, vous devez masquer le répertoire des instantanés en exécutant la commande suivante sur le système de stockage ONTAP :

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
Vous pouvez activer le répertoire de snapshots en exécutant la commande suivante pour chaque volume nas-economy, en remplaçant `<volume-UUID>` avec l'UUID du volume que vous souhaitez modifier :

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: Vous pouvez activer par défaut les répertoires de snapshots pour les nouveaux volumes en configurant l'option de configuration du backend Trident . `snapshotDir` à `true` .  Les volumes existants ne sont pas affectés.



== Protection des données avec les machines virtuelles KubeVirt

Trident Protect 24.10 et 24.10.1 et versions ultérieures ont un comportement différent lorsque vous protégez des applications exécutées sur des machines virtuelles KubeVirt. Pour les deux versions, vous pouvez activer ou désactiver le gel et le dégel du système de fichiers pendant les opérations de protection des données.


NOTE: Lors des opérations de restauration, tout `VirtualMachineSnapshots` Les éléments créés pour une machine virtuelle (VM) ne sont pas restaurés.

.Trident Protect 24.10
Trident Protect 24.10 ne garantit pas automatiquement un état cohérent pour les systèmes de fichiers de machines virtuelles KubeVirt lors des opérations de protection des données. Si vous souhaitez protéger les données de votre machine virtuelle KubeVirt à l'aide de Trident Protect 24.10, vous devez activer manuellement la fonctionnalité de gel/dégel des systèmes de fichiers avant l'opération de protection des données. Cela garantit que les systèmes de fichiers sont dans un état cohérent.

Vous pouvez configurer Trident Protect 24.10 pour gérer le gel et le dégel du système de fichiers de la machine virtuelle lors des opérations de protection des données.link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["configuration de la virtualisation"^] puis en utilisant la commande suivante :

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident Protect 24.10.1 et versions ultérieures
À partir de Trident Protect 24.10.1, Trident Protect gèle et débloque automatiquement les systèmes de fichiers KubeVirt lors des opérations de protection des données. Vous pouvez désactiver ce comportement automatique à l'aide de la commande suivante :

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----


== Exigences pour la réplication SnapMirror

La réplication NetApp SnapMirror est disponible pour une utilisation avec Trident Protect pour les solutions ONTAP suivantes :

* Clusters NetApp FAS, AFF et ASA sur site
* ONTAP Select NetApp ONTAP
* NetApp Cloud Volumes ONTAP
* Amazon FSx for NetApp ONTAP




=== Configuration requise pour la réplication SnapMirror dans un cluster ONTAP

Assurez-vous que votre cluster ONTAP répond aux exigences suivantes si vous prévoyez d'utiliser la réplication SnapMirror :

* * NetApp Trident* : NetApp Trident doit exister à la fois sur les clusters Kubernetes source et de destination qui utilisent ONTAP comme backend. Trident Protect prend en charge la réplication avec la technologie NetApp SnapMirror utilisant des classes de stockage reposant sur les pilotes suivants :
+
** `ontap-nas`: NFS
** `ontap-san`: iSCSI
** `ontap-san`: FC
** `ontap-san`: NVMe/TCP (nécessite au minimum la version ONTAP 9.15.1)


* *Licences* : Les licences asynchrones ONTAP SnapMirror utilisant le module de protection des données doivent être activées sur les clusters ONTAP source et de destination.  Se référer à https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["Présentation des licences SnapMirror dans ONTAP"^] pour plus d'informations.
+
À partir d' ONTAP 9.10.1, toutes les licences sont fournies sous forme de fichier de licence NetApp (NLF), qui est un fichier unique permettant d'activer plusieurs fonctionnalités.  Se référer àlink:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licences incluses avec ONTAP One"^] pour plus d'informations.

+

NOTE: Seule la protection asynchrone SnapMirror est prise en charge.





=== Considérations relatives au peering pour la réplication SnapMirror

Si vous prévoyez d'utiliser le peering de stockage backend, assurez-vous que votre environnement réponde aux exigences suivantes :

* *Cluster et SVM* : Les backends de stockage ONTAP doivent être appariés.  Se référer à https://docs.netapp.com/us-en/ontap/peering/index.html["Aperçu du peering de clusters et de SVM"^] pour plus d'informations.
+

NOTE: Assurez-vous que les noms SVM utilisés dans la relation de réplication entre deux clusters ONTAP sont uniques.

* * NetApp Trident et SVM * : Les SVM distants appariés doivent être disponibles pour NetApp Trident sur le cluster de destination.
* *Systèmes de stockage backend gérés* : Vous devez ajouter et gérer des systèmes de stockage backend ONTAP dans Trident Protect pour créer une relation de réplication.




=== Configuration Trident / ONTAP pour la réplication SnapMirror

Trident Protect exige que vous configuriez au moins un système de stockage dorsal prenant en charge la réplication pour les clusters source et de destination. Si les clusters source et de destination sont identiques, l'application de destination doit utiliser un système de stockage différent de celui de l'application source pour une résilience optimale.



=== Configuration requise pour la réplication SnapMirror dans un cluster Kubernetes

Assurez-vous que vos clusters Kubernetes répondent aux exigences suivantes :

* *Accessibilité à AppVault* : Les clusters source et de destination doivent avoir un accès réseau pour lire et écrire dans AppVault pour la réplication des objets d’application.
* *Connectivité réseau* : Configurez les règles de pare-feu, les autorisations de compartiment et les listes d’adresses IP autorisées pour permettre la communication entre les deux clusters et AppVault via les réseaux WAN.



NOTE: De nombreux environnements d'entreprise mettent en œuvre des politiques de pare-feu strictes sur les connexions WAN.  Vérifiez ces exigences réseau auprès de votre équipe d'infrastructure avant de configurer la réplication.
